Repository exadg/exadg, pull requests merged in 2021-06, with the labels that each got.

#82 Actually use subcommunicator for PETSc matrix
  include/exadg/operators/multigrid_operator.h
  include/exadg/operators/multigrid_operator_base.h
  include/exadg/operators/operator_base.cpp
  include/exadg/operators/operator_base.h
  include/exadg/poisson/driver.cpp
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/spatial_discretization/operator.h
  include/exadg/solvers_and_preconditioners/preconditioners/preconditioner_amg.h
Labels: performance

#84 Use ExaDG::Grid for function verify_boundary_conditions()
  include/exadg/compressible_navier_stokes/driver.cpp
  include/exadg/convection_diffusion/driver.cpp
  include/exadg/fluid_structure_interaction/driver.cpp
  include/exadg/functions_and_boundary_conditions/verify_boundary_conditions.h
  include/exadg/incompressible_flow_with_transport/driver.cpp
  include/exadg/incompressible_navier_stokes/driver.cpp
  include/exadg/incompressible_navier_stokes/driver_precursor.cpp
  include/exadg/poisson/driver.cpp
  include/exadg/structure/driver.cpp
Labels: refactoring

#90 refactor IncNS::BoundaryDescriptor
  applications/fluid_structure_interaction/bending_wall/application.h
  applications/fluid_structure_interaction/cylinder_with_flag/application.h
  applications/fluid_structure_interaction/pressure_wave/application.h
  applications/fluid_structure_interaction/template/application.h
  applications/incompressible_flow_with_transport/differentially_heated_cavity/application.h
  applications/incompressible_flow_with_transport/mantle_convection/application.h
  applications/incompressible_flow_with_transport/rayleigh_benard/application.h
  applications/incompressible_flow_with_transport/rising_bubble/application.h
  applications/incompressible_flow_with_transport/template/application.h
  applications/incompressible_navier_stokes/backward_facing_step/application.h
  applications/incompressible_navier_stokes/beltrami/application.h
  applications/incompressible_navier_stokes/cavity/application.h
  applications/incompressible_navier_stokes/couette/application.h
  applications/incompressible_navier_stokes/fda_benchmark/application.h
  applications/incompressible_navier_stokes/flow_past_cylinder/application.h
  applications/incompressible_navier_stokes/free_stream/application.h
  applications/incompressible_navier_stokes/kelvin_helmholtz/application.h
  applications/incompressible_navier_stokes/kovasznay/application.h
  applications/incompressible_navier_stokes/orr_sommerfeld/application.h
  applications/incompressible_navier_stokes/periodic_hill/application.h
  applications/incompressible_navier_stokes/poiseuille/application.h
  applications/incompressible_navier_stokes/shear_layer/application.h
  applications/incompressible_navier_stokes/stokes_manufactured/application.h
  applications/incompressible_navier_stokes/taylor_green_vortex/application.h
  applications/incompressible_navier_stokes/template/application.h
  applications/incompressible_navier_stokes/template_precursor/application.h
  applications/incompressible_navier_stokes/throughput/application.h
  applications/incompressible_navier_stokes/turbulent_channel/application.h
  applications/incompressible_navier_stokes/vortex/application.h
  include/exadg/fluid_structure_interaction/driver.cpp
  include/exadg/fluid_structure_interaction/driver.h
  include/exadg/fluid_structure_interaction/user_interface/application_base.h
  include/exadg/incompressible_flow_with_transport/driver.cpp
  include/exadg/incompressible_flow_with_transport/driver.h
  include/exadg/incompressible_navier_stokes/driver.cpp
  include/exadg/incompressible_navier_stokes/driver.h
  include/exadg/incompressible_navier_stokes/driver_precursor.cpp
  include/exadg/incompressible_navier_stokes/driver_precursor.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/create_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/continuity_penalty_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/convective_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/divergence_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/gradient_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/momentum_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/projection_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/viscous_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/weak_boundary_conditions.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/incompressible_navier_stokes/user_interface/application_base.h
  include/exadg/incompressible_navier_stokes/user_interface/boundary_descriptor.h
Labels: refactoring

#86 Refactor CompNS::BoundaryDescriptor
  applications/compressible_navier_stokes/couette/application.h
  applications/compressible_navier_stokes/euler_vortex/application.h
  applications/compressible_navier_stokes/manufactured_solution/application.h
  applications/compressible_navier_stokes/poiseuille/application.h
  applications/compressible_navier_stokes/shear_flow/application.h
  applications/compressible_navier_stokes/taylor_green/application.h
  applications/compressible_navier_stokes/template/application.h
  applications/compressible_navier_stokes/turbulent_channel/application.h
  include/exadg/compressible_navier_stokes/driver.cpp
  include/exadg/compressible_navier_stokes/driver.h
  include/exadg/compressible_navier_stokes/spatial_discretization/kernels_and_operators.h
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.cpp
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.h
  include/exadg/compressible_navier_stokes/user_interface/application_base.h
  include/exadg/compressible_navier_stokes/user_interface/boundary_descriptor.h
Labels: refactoring

#93 consistently use std::make_shared
  include/exadg/compressible_navier_stokes/driver.cpp
  include/exadg/compressible_navier_stokes/solver.h
  include/exadg/compressible_navier_stokes/throughput.h
  include/exadg/compressible_navier_stokes/time_integration/time_int_explicit_runge_kutta.cpp
  include/exadg/convection_diffusion/driver.cpp
  include/exadg/convection_diffusion/solver.h
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operators/combined_operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operators/convective_operator.h
  include/exadg/convection_diffusion/throughput.h
  include/exadg/convection_diffusion/time_integration/time_int_bdf.cpp
  include/exadg/convection_diffusion/time_integration/time_int_explicit_runge_kutta.cpp
  include/exadg/convection_diffusion/user_interface/application_base.h
  include/exadg/fluid_structure_interaction/driver.cpp
  include/exadg/fluid_structure_interaction/solver.h
  include/exadg/functions_and_boundary_conditions/interface_coupling.h
  include/exadg/grid/grid.h
  include/exadg/incompressible_flow_with_transport/driver.cpp
  include/exadg/incompressible_flow_with_transport/solver.h
  include/exadg/incompressible_navier_stokes/driver.cpp
  include/exadg/incompressible_navier_stokes/driver_precursor.cpp
  include/exadg/incompressible_navier_stokes/solver.h
  include/exadg/incompressible_navier_stokes/solver_precursor.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/convective_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/momentum_operator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/projection_operator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/incompressible_navier_stokes/throughput.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf.cpp
  include/exadg/incompressible_navier_stokes/user_interface/application_base.h
  include/exadg/operators/operator_base.cpp
  include/exadg/poisson/driver.cpp
  include/exadg/poisson/solver.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/throughput.h
  include/exadg/postprocessor/kinetic_energy_spectrum.cpp
  include/exadg/solvers_and_preconditioners/multigrid/coarse_grid_solvers.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_algorithm.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_global_refinement.cpp
  include/exadg/solvers_and_preconditioners/preconditioners/elementwise_preconditioners.h
  include/exadg/solvers_and_preconditioners/solvers/wrapper_elementwise_solvers.h
  include/exadg/structure/driver.cpp
  include/exadg/structure/preconditioners/multigrid_preconditioner.cpp
  include/exadg/structure/solver.h
  include/exadg/structure/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operators/nonlinear_operator.cpp
  include/exadg/structure/throughput.h
  include/exadg/utilities/timer_tree.h
Labels: refactoring

#92 improve const correctness
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.cpp
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.h
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operator.h
  include/exadg/convection_diffusion/spatial_discretization/operators/combined_operator.h
  include/exadg/convection_diffusion/spatial_discretization/operators/convective_operator.h
  include/exadg/convection_diffusion/spatial_discretization/operators/diffusive_operator.h
  include/exadg/convection_diffusion/spatial_discretization/operators/weak_boundary_conditions.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/create_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/poisson/spatial_discretization/laplace_operator.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/spatial_discretization/operator.h
  include/exadg/poisson/spatial_discretization/weak_boundary_conditions.h
  include/exadg/structure/material/material_handler.h
  include/exadg/structure/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operator.h
  include/exadg/structure/spatial_discretization/operators/boundary_conditions.h
  include/exadg/structure/spatial_discretization/operators/elasticity_operator_base.h
Labels: software design

#87 Allow to set up AMG on an arbitrary mesh level for global coarsening
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
Labels: performance
