Repository exadg/exadg, pull requests merged in 2021-12, with the labels that each got.

#105 Refactor time step calculation and related interfaces
  applications/compressible_navier_stokes/couette/tests/couette.output
  applications/compressible_navier_stokes/euler_vortex/tests/euler_vortex.output
  applications/compressible_navier_stokes/manufactured_solution/tests/manufactured.output
  applications/compressible_navier_stokes/shear_flow/tests/shear_flow.output
  applications/convection_diffusion/deforming_hill/tests/convective_explicit_time_int.output
  applications/convection_diffusion/rotating_hill/tests/convective_implicit_time_int.output
  applications/convection_diffusion/sine_wave/tests/explicit_time_int.output
  applications/incompressible_navier_stokes/free_stream/tests/coupled_bdf2_moving_mesh.output
  applications/incompressible_navier_stokes/free_stream/tests/coupled_bdf2_static_mesh.output
  applications/incompressible_navier_stokes/poiseuille/tests/parabolic_inflow.output
  applications/incompressible_navier_stokes/poiseuille/tests/parabolic_inflow_symmetry_bc.output
  applications/incompressible_navier_stokes/poiseuille/tests/periodic_bc.output
  applications/incompressible_navier_stokes/poiseuille/tests/pressure_inflow.output
  include/exadg/compressible_navier_stokes/spatial_discretization/interface.h
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.cpp
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.h
  include/exadg/compressible_navier_stokes/time_integration/time_int_explicit_runge_kutta.cpp
  include/exadg/convection_diffusion/spatial_discretization/interface.h
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operator.h
  include/exadg/convection_diffusion/time_integration/time_int_bdf.cpp
  include/exadg/convection_diffusion/time_integration/time_int_explicit_runge_kutta.cpp
  include/exadg/incompressible_navier_stokes/driver.cpp
  include/exadg/incompressible_navier_stokes/postprocessor/output_generator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_coupled_solver.cpp
  include/exadg/time_integration/time_step_calculation.h
Labels: refactoring, software design

#112 remove IncNS::SpatialOperatorBase::get_param()
  include/exadg/incompressible_navier_stokes/postprocessor/output_generator.cpp
  include/exadg/incompressible_navier_stokes/postprocessor/output_generator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
Labels: bugfix, software design

#114 shift implementation of Structure::InputParameters to .cpp file
  CMakeLists.txt
  include/exadg/structure/user_interface/input_parameters.cpp
  include/exadg/structure/user_interface/input_parameters.h
Labels: C++, refactoring

#116 add TriangulationType::Serial
  include/exadg/grid/enum_types.cpp
  include/exadg/grid/enum_types.h
  include/exadg/grid/grid.h
Labels: new feature

#117 Adapt to new class names in deal.II for evaluation
  include/exadg/matrix_free/resolve_templates.h
Labels: do not merge, deal.II update

#118 Add dealii interface for optional petsc
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_parameters.h
Labels: do not merge

#121 redesign #ifdef's for Trilinos and Petsc
  include/exadg/solvers_and_preconditioners/multigrid/coarse_grid_solvers.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_parameters.h
  include/exadg/solvers_and_preconditioners/preconditioners/preconditioner_amg.h
  include/exadg/structure/preconditioners/amg_preconditioner.h
Labels: refactoring, software design
