Repository exadg/exadg, pull requests merged in 2021-05, with the labels that each got.

#61 Avoid some redundant operations in MultigridAlgorithm
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_algorithm.h
Labels: performance

#64 adjust config_dealii.sh script
  scripts/config_dealii.sh
  scripts/supermuc-ng/config_dealii.sh
Labels: build system

#63 fix compilation error for timer.cc test
  tests/utilities/timer.cc
Labels: bugfix, testing

#62 create output directory if not already existing
  applications/compressible_navier_stokes/taylor_green/application.h
  applications/compressible_navier_stokes/turbulent_channel/application.h
  applications/incompressible_navier_stokes/backward_facing_step/application.h
  applications/incompressible_navier_stokes/backward_facing_step/include/postprocessor.h
  applications/incompressible_navier_stokes/fda_benchmark/application.h
  applications/incompressible_navier_stokes/fda_benchmark/include/postprocessor.h
  applications/incompressible_navier_stokes/flow_past_cylinder/application.h
  applications/incompressible_navier_stokes/kelvin_helmholtz/application.h
  applications/incompressible_navier_stokes/orr_sommerfeld/application.h
  applications/incompressible_navier_stokes/orr_sommerfeld/include/perturbation_energy.h
  applications/incompressible_navier_stokes/periodic_hill/application.h
  applications/incompressible_navier_stokes/shear_layer/application.h
  applications/incompressible_navier_stokes/taylor_green_vortex/application.h
  applications/incompressible_navier_stokes/turbulent_channel/application.h
  include/exadg/compressible_navier_stokes/postprocessor/output_generator.cpp
  include/exadg/convection_diffusion/postprocessor/postprocessor.h
  include/exadg/incompressible_navier_stokes/postprocessor/divergence_and_mass_error.cpp
  include/exadg/incompressible_navier_stokes/postprocessor/divergence_and_mass_error.h
  include/exadg/incompressible_navier_stokes/postprocessor/flow_rate_calculator.cpp
  include/exadg/incompressible_navier_stokes/postprocessor/flow_rate_calculator.h
  include/exadg/incompressible_navier_stokes/postprocessor/inflow_data_calculator.cpp
  include/exadg/incompressible_navier_stokes/postprocessor/line_plot_calculation.cpp
  include/exadg/incompressible_navier_stokes/postprocessor/line_plot_calculation_statistics.cpp
  include/exadg/incompressible_navier_stokes/postprocessor/line_plot_calculation_statistics.h
  include/exadg/incompressible_navier_stokes/postprocessor/line_plot_calculation_statistics_homogeneous.cpp
  include/exadg/incompressible_navier_stokes/postprocessor/line_plot_calculation_statistics_homogeneous.h
  include/exadg/incompressible_navier_stokes/postprocessor/line_plot_data.h
  include/exadg/incompressible_navier_stokes/postprocessor/mean_velocity_calculator.cpp
  include/exadg/incompressible_navier_stokes/postprocessor/mean_velocity_calculator.h
  include/exadg/incompressible_navier_stokes/postprocessor/output_generator.cpp
  include/exadg/postprocessor/error_calculation.cpp
  include/exadg/postprocessor/error_calculation.h
  include/exadg/postprocessor/kinetic_energy_calculation.cpp
  include/exadg/postprocessor/kinetic_energy_calculation.h
  include/exadg/postprocessor/kinetic_energy_spectrum.cpp
  include/exadg/postprocessor/kinetic_energy_spectrum.h
  include/exadg/postprocessor/lift_and_drag_calculation.cpp
  include/exadg/postprocessor/lift_and_drag_calculation.h
  include/exadg/postprocessor/output_generator_scalar.cpp
  include/exadg/postprocessor/pressure_difference_calculation.cpp
  include/exadg/postprocessor/pressure_difference_calculation.h
  include/exadg/postprocessor/statistics_manager.cpp
  include/exadg/postprocessor/statistics_manager.h
  include/exadg/structure/postprocessor/output_generator.cpp
  include/exadg/utilities/create_directories.h
Labels: enhancement

#65 Rename variables in OutputDataBase for consistency
  applications/compressible_navier_stokes/couette/application.h
  applications/compressible_navier_stokes/euler_vortex/application.h
  applications/compressible_navier_stokes/manufactured_solution/application.h
  applications/compressible_navier_stokes/poiseuille/application.h
  applications/compressible_navier_stokes/shear_flow/application.h
  applications/compressible_navier_stokes/taylor_green/application.h
  applications/compressible_navier_stokes/turbulent_channel/application.h
  applications/convection_diffusion/boundary_layer/application.h
  applications/convection_diffusion/const_rhs/application.h
  applications/convection_diffusion/decaying_hill/application.h
  applications/convection_diffusion/deforming_hill/application.h
  applications/convection_diffusion/rotating_hill/application.h
  applications/convection_diffusion/sine_wave/application.h
  applications/fluid_structure_interaction/bending_wall/application.h
  applications/fluid_structure_interaction/cylinder_with_flag/application.h
  applications/fluid_structure_interaction/pressure_wave/application.h
  applications/incompressible_flow_with_transport/differentially_heated_cavity/application.h
  applications/incompressible_flow_with_transport/mantle_convection/application.h
  applications/incompressible_flow_with_transport/rayleigh_benard/application.h
  applications/incompressible_flow_with_transport/rising_bubble/application.h
  applications/incompressible_navier_stokes/backward_facing_step/application.h
  applications/incompressible_navier_stokes/beltrami/application.h
  applications/incompressible_navier_stokes/cavity/application.h
  applications/incompressible_navier_stokes/couette/application.h
  applications/incompressible_navier_stokes/fda_benchmark/application.h
  applications/incompressible_navier_stokes/fda_benchmark/application_poisson.h
  applications/incompressible_navier_stokes/flow_past_cylinder/application.h
  applications/incompressible_navier_stokes/free_stream/application.h
  applications/incompressible_navier_stokes/kelvin_helmholtz/application.h
  applications/incompressible_navier_stokes/kovasznay/application.h
  applications/incompressible_navier_stokes/orr_sommerfeld/application.h
  applications/incompressible_navier_stokes/periodic_hill/application.h
  applications/incompressible_navier_stokes/poiseuille/application.h
  applications/incompressible_navier_stokes/shear_layer/application.h
  applications/incompressible_navier_stokes/stokes_manufactured/application.h
  applications/incompressible_navier_stokes/taylor_green_vortex/application.h
  applications/incompressible_navier_stokes/turbulent_channel/application.h
  applications/incompressible_navier_stokes/vortex/application.h
  applications/incompressible_navier_stokes/vortex/vortex_backup.h
  applications/poisson/gaussian/application.h
  applications/poisson/sine/application.h
  applications/poisson/slit/application.h
  applications/structure/bar/application.h
  applications/structure/beam/application.h
  applications/structure/can/application.h
  applications/structure/manufactured/application.h
  include/exadg/compressible_navier_stokes/postprocessor/output_generator.cpp
  include/exadg/incompressible_navier_stokes/postprocessor/output_generator.cpp
  include/exadg/postprocessor/error_calculation.cpp
  include/exadg/postprocessor/error_calculation.h
  include/exadg/postprocessor/kinetic_energy_spectrum.cpp
  include/exadg/postprocessor/output_data_base.h
  include/exadg/postprocessor/output_generator_scalar.cpp
  include/exadg/structure/postprocessor/output_generator.cpp
Labels: refactoring

#67 Optimize matrix-vector product in OperatorBase
  include/exadg/operators/operator_base.cpp
  include/exadg/operators/operator_base.h
Labels: performance

#68 Optimizations for interface to PETSc/BoomerAMG preconditioner
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/solvers_and_preconditioners/multigrid/coarse_grid_solvers.h
  include/exadg/solvers_and_preconditioners/preconditioners/preconditioner_amg.h
  include/exadg/solvers_and_preconditioners/utilities/petsc_operation.h
Labels: performance

#69 Drop MPI processes from coarser grid level in global coarsening
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/utilities/mpi.h
Labels: performance

#73 Add some forgotten vec.zero_out_ghost_values()
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_c.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_p.cpp
Labels: bugfix

#72 Introduce utility functions create_operator() and create_time_integrator()
  include/exadg/convection_diffusion/driver.cpp
  include/exadg/convection_diffusion/driver.h
  include/exadg/convection_diffusion/time_integration/create_time_integrator.h
  include/exadg/convection_diffusion/time_integration/time_int_bdf.cpp
  include/exadg/convection_diffusion/time_integration/time_int_bdf.h
  include/exadg/fluid_structure_interaction/driver.cpp
  include/exadg/fluid_structure_interaction/driver.h
  include/exadg/incompressible_flow_with_transport/driver.cpp
  include/exadg/incompressible_flow_with_transport/driver.h
  include/exadg/incompressible_navier_stokes/driver.cpp
  include/exadg/incompressible_navier_stokes/driver.h
  include/exadg/incompressible_navier_stokes/driver_precursor.cpp
  include/exadg/incompressible_navier_stokes/driver_precursor.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/create_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/incompressible_navier_stokes/time_integration/create_time_integrator.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_coupled_solver.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_coupled_solver.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_dual_splitting.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_pressure_correction.h
Labels: refactoring, software design

#74 Avoid implicit float-to-int conversions
  applications/incompressible_navier_stokes/fda_benchmark/application.h
  applications/incompressible_navier_stokes/orr_sommerfeld/include/orr_sommerfeld_equation.h
  include/exadg/compressible_navier_stokes/driver.h
  include/exadg/convection_diffusion/driver.h
  include/exadg/convection_diffusion/time_integration/time_int_bdf.cpp
  include/exadg/convection_diffusion/time_integration/time_int_explicit_runge_kutta.cpp
  include/exadg/incompressible_navier_stokes/driver.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf.cpp
  include/exadg/poisson/driver.h
  include/exadg/postprocessor/kinetic_energy_spectrum.cpp
  include/exadg/postprocessor/mirror_dof_vector_taylor_green.h
  include/exadg/postprocessor/spectral_analysis/bijection.h
  include/exadg/postprocessor/spectral_analysis/interpolation.h
  include/exadg/postprocessor/spectral_analysis/permutation.h
  include/exadg/postprocessor/spectral_analysis/spectrum.h
  include/exadg/postprocessor/statistics_manager.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_p.cpp
  include/exadg/structure/driver.h
  include/exadg/utilities/hypercube_resolution_parameters.h
Labels: C++

#77 remove file postprocessor/spectral_analysis/bijection.h
  include/exadg/postprocessor/kinetic_energy_spectrum.cpp
  include/exadg/postprocessor/spectral_analysis/bijection.h
  include/exadg/postprocessor/spectral_analysis/interpolation.h
  include/exadg/postprocessor/spectral_analysis/setup.h
Labels: deal.II update, refactoring

#75 refactor MatrixFreeData to avoid code duplication
  include/exadg/compressible_navier_stokes/driver.cpp
  include/exadg/compressible_navier_stokes/driver.h
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.h
  include/exadg/convection_diffusion/driver.cpp
  include/exadg/convection_diffusion/driver.h
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.cpp
  include/exadg/convection_diffusion/spatial_discretization/operator.h
  include/exadg/convection_diffusion/time_integration/time_int_bdf.cpp
  include/exadg/fluid_structure_interaction/driver.cpp
  include/exadg/fluid_structure_interaction/driver.h
  include/exadg/incompressible_flow_with_transport/driver.cpp
  include/exadg/incompressible_flow_with_transport/driver.h
  include/exadg/incompressible_navier_stokes/driver.cpp
  include/exadg/incompressible_navier_stokes/driver.h
  include/exadg/incompressible_navier_stokes/driver_precursor.cpp
  include/exadg/incompressible_navier_stokes/driver_precursor.h
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf.cpp
  include/exadg/matrix_free/categorization.h
  include/exadg/matrix_free/matrix_free_data.h
  include/exadg/poisson/driver.cpp
  include/exadg/poisson/driver.h
  include/exadg/poisson/spatial_discretization/operator.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/structure/driver.cpp
  include/exadg/structure/driver.h
  include/exadg/structure/preconditioners/multigrid_preconditioner.cpp
  include/exadg/structure/spatial_discretization/operator.h
Labels: code duplication, software design

#79 introduce pure virtual MovingMeshInterface class
  include/exadg/convection_diffusion/driver.cpp
  include/exadg/convection_diffusion/driver.h
  include/exadg/convection_diffusion/time_integration/create_time_integrator.h
  include/exadg/convection_diffusion/time_integration/time_int_bdf.cpp
  include/exadg/convection_diffusion/time_integration/time_int_bdf.h
  include/exadg/fluid_structure_interaction/driver.cpp
  include/exadg/fluid_structure_interaction/driver.h
  include/exadg/grid/moving_mesh_base.h
  include/exadg/grid/moving_mesh_elasticity.h
  include/exadg/grid/moving_mesh_function.h
  include/exadg/grid/moving_mesh_interface.h
  include/exadg/grid/moving_mesh_poisson.h
  include/exadg/incompressible_flow_with_transport/driver.cpp
  include/exadg/incompressible_flow_with_transport/driver.h
  include/exadg/incompressible_navier_stokes/driver.cpp
  include/exadg/incompressible_navier_stokes/driver.h
  include/exadg/incompressible_navier_stokes/time_integration/create_time_integrator.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_coupled_solver.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_coupled_solver.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_dual_splitting.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_pressure_correction.h
Labels: refactoring, software design

#81 Avoid deprecated functionality of deal.II
  include/exadg/grid/find_all_active_cells_around_point.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_coupled_solver.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_pressure_correction.cpp
  include/exadg/operators/inverse_mass_operator.h
  include/exadg/postprocessor/write_output.h
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_h.cpp
  include/exadg/solvers_and_preconditioners/preconditioners/preconditioner_amg.h
  include/exadg/solvers_and_preconditioners/utilities/check_multigrid.h
  include/exadg/solvers_and_preconditioners/utilities/compute_eigenvalues.h
  include/exadg/solvers_and_preconditioners/utilities/invert_diagonal.h
  include/exadg/solvers_and_preconditioners/utilities/petsc_operation.h
  include/exadg/solvers_and_preconditioners/utilities/verify_calculation_of_diagonal.h
Labels: deal.II update
