Repository exadg/exadg, pull requests merged in 2021-03, with the labels that each got.

#24 fix bug related to *Mg with hanging nodes* MR
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.cpp
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
Labels: bugfix, high priority

#25 Multigrid refactoring
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_input_parameters.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_input_parameters.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
Labels: refactoring, software design

#26 forgot to call new function initialize_coarse_grid_triangulations()
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
Labels: bugfix

#28 reduce compile time for multigrid by forward declarations
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/grid/moving_mesh_elasticity.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
Labels: C++, software design

#29 Simplify tria.get_communicator() calls according to updates in deal.II
  applications/incompressible_navier_stokes/fda_benchmark/include/postprocessor.h
  applications/incompressible_navier_stokes/orr_sommerfeld/include/perturbation_energy.h
  include/exadg/compressible_navier_stokes/driver.h
  include/exadg/compressible_navier_stokes/postprocessor/output_generator.h
  include/exadg/compressible_navier_stokes/postprocessor/postprocessor.h
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.h
  include/exadg/convection_diffusion/driver.h
  include/exadg/convection_diffusion/postprocessor/postprocessor.h
  include/exadg/convection_diffusion/spatial_discretization/operator.h
  include/exadg/convection_diffusion/time_integration/driver_steady_problems.h
  include/exadg/fluid_structure_interaction/driver.h
  include/exadg/functions_and_boundary_conditions/interface_coupling.h
  include/exadg/incompressible_flow_with_transport/driver.h
  include/exadg/incompressible_navier_stokes/driver.h
  include/exadg/incompressible_navier_stokes/driver_precursor.h
  include/exadg/incompressible_navier_stokes/postprocessor/divergence_and_mass_error.h
  include/exadg/incompressible_navier_stokes/postprocessor/flow_rate_calculator.h
  include/exadg/incompressible_navier_stokes/postprocessor/inflow_data_calculator.h
  include/exadg/incompressible_navier_stokes/postprocessor/line_plot_calculation.h
  include/exadg/incompressible_navier_stokes/postprocessor/mean_velocity_calculator.h
  include/exadg/incompressible_navier_stokes/postprocessor/output_generator.h
  include/exadg/incompressible_navier_stokes/postprocessor/postprocessor.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/incompressible_navier_stokes/time_integration/driver_steady_problems.h
  include/exadg/operators/operator_base.cpp
  include/exadg/poisson/driver.h
  include/exadg/poisson/postprocessor/postprocessor.h
  include/exadg/poisson/spatial_discretization/operator.h
  include/exadg/postprocessor/error_calculation.h
  include/exadg/postprocessor/kinetic_energy_calculation.h
  include/exadg/postprocessor/kinetic_energy_spectrum.h
  include/exadg/postprocessor/lift_and_drag_calculation.h
  include/exadg/postprocessor/mean_scalar_calculation.h
  include/exadg/postprocessor/mirror_dof_vector_taylor_green.h
  include/exadg/postprocessor/output_generator_scalar.h
  include/exadg/postprocessor/pressure_difference_calculation.h
  include/exadg/postprocessor/statistics_manager.cpp
  include/exadg/solvers_and_preconditioners/multigrid/coarse_grid_solvers.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_algorithm.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/solvers_and_preconditioners/solvers/iterative_solvers_dealii_wrapper.h
  include/exadg/structure/postprocessor/output_generator.h
  include/exadg/structure/postprocessor/postprocessor.h
  include/exadg/structure/spatial_discretization/operator.h
  include/exadg/structure/time_integration/driver_quasi_static_problems.h
  include/exadg/structure/time_integration/driver_steady_problems.h
  include/exadg/structure/time_integration/time_int_gen_alpha.h
  include/exadg/time_integration/time_int_base.h
  include/exadg/utilities/dynamic_convergence_table.h
Labels: deal.II update, software design

#30 fix bug related to accessing wrong mapping data for global coarsening MG
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/solvers_and_preconditioners/multigrid/transfer/mg_transfer_global_coarsening.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfer/mg_transfer_global_coarsening.h
Labels: bugfix

#31 Renaming Multigrid
  CMakeLists.txt
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operator.h
  include/exadg/convection_diffusion/user_interface/input_parameters.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/incompressible_navier_stokes/user_interface/input_parameters.h
  include/exadg/operators/operator_base.cpp
  include/exadg/operators/operator_base.h
  include/exadg/poisson/preconditioners/multigrid_preconditioner.cpp
  include/exadg/poisson/preconditioners/multigrid_preconditioner.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/spatial_discretization/operator.h
  include/exadg/solvers_and_preconditioners/multigrid/coarse_grid_solvers.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_algorithm.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/solvers_and_preconditioners/multigrid/smoothers/cg_smoother.h
  include/exadg/solvers_and_preconditioners/multigrid/smoothers/gmres_smoother.h
  include/exadg/solvers_and_preconditioners/multigrid/smoothers/jacobi_smoother.h
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer.h
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_c.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_c.h
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_global_coarsening.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_global_coarsening.h
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_global_refinement.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_global_refinement.h
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_h.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_h.h
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_p.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_p.h
  include/exadg/solvers_and_preconditioners/preconditioners/block_jacobi_preconditioner.h
  include/exadg/solvers_and_preconditioners/preconditioners/elementwise_preconditioners.h
  include/exadg/solvers_and_preconditioners/preconditioners/enum_types.cpp
  include/exadg/solvers_and_preconditioners/preconditioners/enum_types.h
  include/exadg/solvers_and_preconditioners/preconditioners/inverse_mass_preconditioner.h
  include/exadg/solvers_and_preconditioners/preconditioners/jacobi_preconditioner.h
  include/exadg/solvers_and_preconditioners/preconditioners/preconditioner_amg.h
  include/exadg/solvers_and_preconditioners/preconditioners/preconditioner_base.h
  include/exadg/solvers_and_preconditioners/solvers/wrapper_elementwise_solvers.h
  include/exadg/solvers_and_preconditioners/utilities/block_jacobi_matrices.h
  include/exadg/solvers_and_preconditioners/utilities/check_multigrid.h
  include/exadg/solvers_and_preconditioners/utilities/compute_eigenvalues.h
  include/exadg/solvers_and_preconditioners/utilities/invert_diagonal.h
  include/exadg/solvers_and_preconditioners/utilities/verify_calculation_of_diagonal.h
  include/exadg/structure/preconditioners/amg_preconditioner.h
  include/exadg/structure/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operator.h
  tests/solvers_and_preconditioners/elementwise_gmres.cc
Labels: refactoring, software design

#36 MappingDoFVector: change order of parameters for consistency
  include/exadg/grid/mapping_dof_vector.h
  include/exadg/grid/moving_mesh_elasticity.h
  include/exadg/grid/moving_mesh_poisson.h
Labels: refactoring

#37 implement transfer of mapping for multigrid with global coarsening
  include/exadg/grid/mapping_dof_vector.h
  include/exadg/grid/moving_mesh_base.h
  include/exadg/grid/moving_mesh_elasticity.h
  include/exadg/grid/moving_mesh_function.h
  include/exadg/grid/moving_mesh_poisson.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_global_coarsening.cpp
Labels: new feature

#38 correct description for parameter is_test
  include/exadg/utilities/general_parameters.h
Labels: documentation

#39 make initialize_multigrid() functions for MappingDoFVector free functions
  include/exadg/grid/mapping_dof_vector.h
  include/exadg/grid/moving_mesh_base.h
  include/exadg/grid/moving_mesh_elasticity.h
  include/exadg/grid/moving_mesh_poisson.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
Labels: refactoring

#40 fix bug related to MappingDoFVector changes
  include/exadg/grid/moving_mesh_base.h
  include/exadg/grid/moving_mesh_elasticity.h
  include/exadg/grid/moving_mesh_function.h
  include/exadg/grid/moving_mesh_poisson.h
Labels: bugfix, high priority

#42 Remove Assert in compute_performance_metrics()
  include/exadg/poisson/driver.cpp
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/solvers_and_preconditioners/solvers/iterative_solvers_dealii_wrapper.h
Labels: enhancement, software design

#44 introduce namespace Krylov for iterative solvers such as CG, GMRES,FGMRES
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/spatial_discretization/operator.h
  include/exadg/solvers_and_preconditioners/multigrid/coarse_grid_solvers.h
  include/exadg/solvers_and_preconditioners/solvers/iterative_solvers_dealii_wrapper.h
  include/exadg/solvers_and_preconditioners/solvers/wrapper_elementwise_solvers.h
  include/exadg/structure/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operator.h
Labels: refactoring, software design

#46 Fix aspect ratio output
  include/exadg/incompressible_navier_stokes/postprocessor/output_generator.cpp
Labels: bugfix

#48 add new config_petsc.sh script and adjust config_dealii.sh script
  scripts/config_dealii.sh
  scripts/config_petsc.sh
Labels: build system, documentation

#49 Implement timings for Multigrid using TimerTree
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.h
  include/exadg/poisson/driver.cpp
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/spatial_discretization/operator.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_algorithm.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/solvers_and_preconditioners/preconditioners/preconditioner_base.h
  include/exadg/solvers_and_preconditioners/solvers/iterative_solvers_dealii_wrapper.h
Labels: new feature, software design

#50 Convert level triangulations to p:f:T
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
Labels: enhancement, performance

#47 Implement BoomerAMG via PETSc
  include/exadg/operators/multigrid_operator.h
  include/exadg/operators/multigrid_operator_base.h
  include/exadg/operators/operator_base.cpp
  include/exadg/operators/operator_base.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/spatial_discretization/operator.h
  include/exadg/solvers_and_preconditioners/multigrid/coarse_grid_solvers.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_input_parameters.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_input_parameters.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/preconditioners/preconditioner_amg.h
  include/exadg/solvers_and_preconditioners/utilities/petsc_operation.h
Labels: enhancement, ready to merge

#51 fix compilation error
  include/exadg/solvers_and_preconditioners/preconditioners/preconditioner_amg.h
Labels: bugfix

#52 some more bug fixes and clean-up related to PR #47
  applications/convection_diffusion/const_rhs/application.h
  applications/convection_diffusion/rotating_hill/tests/convective_implicit_time_int.output
  applications/fluid_structure_interaction/bending_wall/application.h
  applications/fluid_structure_interaction/cylinder_with_flag/application.h
  applications/fluid_structure_interaction/pressure_wave/application.h
  applications/incompressible_navier_stokes/backward_facing_step/application.h
  applications/incompressible_navier_stokes/couette/tests/steady_navier_stokes_coupled.output
  applications/incompressible_navier_stokes/fda_benchmark/application.h
  applications/incompressible_navier_stokes/fda_benchmark/application_poisson.h
  applications/incompressible_navier_stokes/flow_past_cylinder/application.h
  applications/incompressible_navier_stokes/free_stream/tests/coupled_bdf2_moving_mesh.output
  applications/incompressible_navier_stokes/free_stream/tests/coupled_bdf2_static_mesh.output
  applications/incompressible_navier_stokes/poiseuille/tests/parabolic_inflow.output
  applications/incompressible_navier_stokes/poiseuille/tests/parabolic_inflow_symmetry_bc.output
  applications/incompressible_navier_stokes/poiseuille/tests/periodic_bc.output
  applications/incompressible_navier_stokes/poiseuille/tests/pressure_inflow.output
  applications/incompressible_navier_stokes/vortex/application.h
  applications/poisson/gaussian/application.h
  applications/poisson/gaussian/tests/gaussian.output
  applications/poisson/sine/application.h
  applications/poisson/sine/tests/cartesian.output
  applications/poisson/sine/tests/curvilinear.output
  applications/poisson/slit/application.h
  applications/structure/bar/application.h
  applications/structure/beam/application.h
  applications/structure/can/application.h
  include/exadg/solvers_and_preconditioners/multigrid/coarse_grid_solvers.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_input_parameters.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_input_parameters.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/preconditioners/preconditioner_amg.h
  include/exadg/structure/preconditioners/amg_preconditioner.h
  include/exadg/structure/spatial_discretization/operator.cpp
  include/exadg/structure/user_interface/enum_types.cpp
  include/exadg/structure/user_interface/enum_types.h
  include/exadg/structure/user_interface/input_parameters.h
Labels: bugfix

#53 Avoid repeated public keyword
  include/exadg/solvers_and_preconditioners/preconditioners/preconditioner_amg.h
Labels: refactoring

#54 Fix memory leak in PETSc operation
  include/exadg/solvers_and_preconditioners/utilities/petsc_operation.h
Labels: bugfix
