Repository exadg/exadg, pull requests merged in 2021-02, with the labels that each got.

#11 remove some old scripts and add #!/bin/sh for others
  scripts/config_dealii.sh
  scripts/config_exadg.sh
  scripts/config_trilinos.sh
  scripts/makempirun
  scripts/makerun
Labels: build system

#16 fix failing tests
  applications/convection_diffusion/boundary_layer/tests/p_convergence.output
  applications/convection_diffusion/rotating_hill/tests/convective_implicit_time_int.output
  applications/incompressible_navier_stokes/couette/tests/steady_navier_stokes_coupled.output
  applications/incompressible_navier_stokes/free_stream/tests/coupled_bdf2_moving_mesh.output
  applications/incompressible_navier_stokes/free_stream/tests/coupled_bdf2_static_mesh.output
  applications/incompressible_navier_stokes/poiseuille/tests/parabolic_inflow.output
  applications/incompressible_navier_stokes/poiseuille/tests/parabolic_inflow_symmetry_bc.output
  applications/incompressible_navier_stokes/poiseuille/tests/periodic_bc.output
  applications/incompressible_navier_stokes/poiseuille/tests/pressure_inflow.output
  applications/poisson/gaussian/tests/gaussian.output
  applications/poisson/sine/tests/cartesian.output
  applications/poisson/sine/tests/curvilinear.output
  applications/structure/manufactured/tests/2d.output
  applications/structure/manufactured/tests/3d.output
Labels: bugfix

#13 fix bug in OperatorBase::add_diagonal()
  include/exadg/operators/operator_base.cpp
Labels: bugfix

#18 MG: avoid code redundancy
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
Labels: software design

#20 Add two asserts in MultigridPreconditionerBase
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
Labels: bugfix

#21 adjust comments related to new multigrid transfer variant
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_input_parameters.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
Labels: refactoring

#17 refactor reinit_cell() for elasticity operator
  include/exadg/structure/spatial_discretization/operators/nonlinear_operator.cpp
Labels: refactoring, software design

#22 fix bug in MovingMeshBase by using ghosted dof-vector
  include/exadg/grid/moving_mesh_base.h
Labels: bugfix

#23 simplify interface in MovingMeshBase
  include/exadg/grid/moving_mesh_base.h
  include/exadg/grid/moving_mesh_elasticity.h
  include/exadg/grid/moving_mesh_function.h
  include/exadg/grid/moving_mesh_poisson.h
Labels: refactoring, software design
