Repository exadg/exadg, pull requests merged in 2022-11, with the labels that each got.

#268 Simplex support for Poisson operator
  applications/poisson/sine/application.h
  include/exadg/grid/grid.h
  include/exadg/grid/grid_data.h
Labels: grid, tets

#269 make Grid::create_triangulation more flexible
  applications/incompressible_navier_stokes/flow_past_cylinder/application.h
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.cpp
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.h
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/grid/enum_types.cpp
  include/exadg/grid/enum_types.h
  include/exadg/grid/grid.h
  include/exadg/grid/grid_data.h
  include/exadg/grid/mapping_dof_vector.h
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.h
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/poisson/preconditioners/multigrid_preconditioner.cpp
  include/exadg/poisson/preconditioners/multigrid_preconditioner.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/structure/preconditioners/multigrid_preconditioner.cpp
  include/exadg/structure/preconditioners/multigrid_preconditioner.h
  include/exadg/structure/spatial_discretization/operator.cpp
Labels: grid

#119 Add test case for flow around sphere
  applications/incompressible_navier_stokes/flow_past_sphere/CMakeLists.txt
  applications/incompressible_navier_stokes/flow_past_sphere/application.h
  applications/incompressible_navier_stokes/flow_past_sphere/include/grid.h
  applications/incompressible_navier_stokes/flow_past_sphere/input.json
  applications/incompressible_navier_stokes/flow_past_sphere/solver.cpp
Labels: enhancement

#270 introduce global coarsening prototype
  prototypes/CMakeLists.txt
  prototypes/global_coarsening.cpp
  prototypes/particles.cpp
Labels: grid, multigrid

#273 Fix a few compile warnings with clang compiler
  include/exadg/compressible_navier_stokes/postprocessor/pointwise_output_generator.cpp
  include/exadg/fluid_structure_interaction/precice/driver_fluid.h
  include/exadg/fluid_structure_interaction/precice/driver_solid.h
  include/exadg/fluid_structure_interaction/precice/quad_coupling.h
  include/exadg/postprocessor/pointwise_output_generator_base.cpp
  prototypes/global_coarsening.cpp
Labels: C++

#280 remove templates from make_sparsity_pattern
  include/exadg/operators/operator_base.cpp
Labels: bugfix

#278 Fix coarse triangulation creation for serial triangulations
  include/exadg/grid/grid.cpp
Labels: bugfix, grid, multigrid

#274 follow-up to #245
  applications/compressible_navier_stokes/turbulent_channel/application.h
  include/exadg/compressible_navier_stokes/postprocessor/output_generator.cpp
  include/exadg/compressible_navier_stokes/postprocessor/postprocessor.cpp
  include/exadg/compressible_navier_stokes/postprocessor/postprocessor.h
  include/exadg/incompressible_navier_stokes/postprocessor/output_generator.cpp
  include/exadg/incompressible_navier_stokes/postprocessor/postprocessor.cpp
  include/exadg/incompressible_navier_stokes/postprocessor/postprocessor.h
  include/exadg/postprocessor/solution_field.h
Labels: refactoring, software design

#286 shift ContainerInterfaceData to separate file
  CMakeLists.txt
  include/exadg/functions_and_boundary_conditions/container_interface_data.cpp
  include/exadg/functions_and_boundary_conditions/container_interface_data.h
  include/exadg/functions_and_boundary_conditions/function_cached.cpp
  include/exadg/functions_and_boundary_conditions/function_cached.h
  include/exadg/functions_and_boundary_conditions/interface_coupling.h
Labels: refactoring

#288 [WIP] choose mesh smoothing
  applications/poisson/sine/application.h
  include/exadg/grid/grid.cpp
  include/exadg/grid/grid.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
Labels: grid, multigrid
