Repository exadg/exadg, pull requests merged in 2022-01, with the labels that each got.

#123 Fix case with precursor
  include/exadg/incompressible_navier_stokes/driver_precursor.cpp
  include/exadg/incompressible_navier_stokes/user_interface/application_base.h
Labels: bugfix

#127 Copy vectors in MGTransferC
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_c.cpp
Labels: bugfix

#126 Refactor InterfaceCoupling
  include/exadg/fluid_structure_interaction/driver.cpp
  include/exadg/functions_and_boundary_conditions/function_cached.h
  include/exadg/functions_and_boundary_conditions/interface_coupling.h
Labels: refactoring, deal.II update

#130 preparations for simplex support
  include/exadg/matrix_free/matrix_free_data.h
Labels: enhancement, high priority

#132 Remove distribute_mg_dofs from field solvers
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/structure/spatial_discretization/operator.cpp
Labels: software design

#142 rename solve_timestep() into do_timestep_solve() for consistency
  include/exadg/compressible_navier_stokes/time_integration/time_int_explicit_runge_kutta.cpp
  include/exadg/compressible_navier_stokes/time_integration/time_int_explicit_runge_kutta.h
  include/exadg/convection_diffusion/time_integration/time_int_bdf.cpp
  include/exadg/convection_diffusion/time_integration/time_int_bdf.h
  include/exadg/convection_diffusion/time_integration/time_int_explicit_runge_kutta.cpp
  include/exadg/convection_diffusion/time_integration/time_int_explicit_runge_kutta.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_coupled_solver.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_coupled_solver.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_dual_splitting.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_pressure_correction.h
  include/exadg/structure/time_integration/time_int_gen_alpha.cpp
  include/exadg/structure/time_integration/time_int_gen_alpha.h
  include/exadg/time_integration/explicit_runge_kutta.h
  include/exadg/time_integration/ssp_runge_kutta.h
  include/exadg/time_integration/time_int_base.cpp
  include/exadg/time_integration/time_int_base.h
  include/exadg/time_integration/time_int_bdf_base.h
  include/exadg/time_integration/time_int_explicit_runge_kutta_base.h
  include/exadg/time_integration/time_int_gen_alpha_base.h
Labels: refactoring

#139 some renaming in drivers for steady problems
  include/exadg/convection_diffusion/driver.cpp
  include/exadg/convection_diffusion/time_integration/driver_steady_problems.cpp
  include/exadg/convection_diffusion/time_integration/driver_steady_problems.h
  include/exadg/incompressible_flow_with_transport/driver.cpp
  include/exadg/incompressible_navier_stokes/driver.cpp
  include/exadg/incompressible_navier_stokes/time_integration/driver_steady_problems.cpp
  include/exadg/incompressible_navier_stokes/time_integration/driver_steady_problems.h
  include/exadg/structure/driver.cpp
  include/exadg/structure/time_integration/driver_quasi_static_problems.cpp
  include/exadg/structure/time_integration/driver_quasi_static_problems.h
  include/exadg/structure/time_integration/driver_steady_problems.cpp
  include/exadg/structure/time_integration/driver_steady_problems.h
Labels: refactoring

#138 a minor simplification in FTI::Driver related to ALE
  include/exadg/convection_diffusion/user_interface/parameters.cpp
  include/exadg/incompressible_flow_with_transport/driver.cpp
Labels: refactoring, ALE

#141 ALE: check for restarted simulation in postprocessing()
  include/exadg/convection_diffusion/time_integration/time_int_bdf.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf.cpp
Labels: ALE

#146 new Grid functionality: perform local refinements
  include/exadg/grid/perform_local_refinements.h
Labels: new feature, refactoring
