Repository exadg/exadg, pull requests merged in 2022-02, with the labels that each got.

#149 minor refactoring/renaming for dual-splitting scheme
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_dual_splitting.h
Labels: refactoring

#152 rename Mortar -> Cached
  applications/fluid_structure_interaction/bending_wall/application.h
  applications/fluid_structure_interaction/cylinder_with_flag/application.h
  applications/fluid_structure_interaction/pressure_wave/application.h
  include/exadg/fluid_structure_interaction/driver.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/convective_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/weak_boundary_conditions.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/user_interface/boundary_descriptor.h
  include/exadg/poisson/spatial_discretization/laplace_operator.cpp
  include/exadg/poisson/spatial_discretization/laplace_operator.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/spatial_discretization/weak_boundary_conditions.h
  include/exadg/poisson/user_interface/boundary_descriptor.h
  include/exadg/structure/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operators/boundary_conditions.h
  include/exadg/structure/spatial_discretization/operators/elasticity_operator_base.cpp
  include/exadg/structure/spatial_discretization/operators/elasticity_operator_base.h
  include/exadg/structure/user_interface/boundary_descriptor.h
Labels: refactoring

#147 Generalize and simplify create grid functionality
  applications/incompressible_navier_stokes/flow_past_cylinder/application.h
  applications/incompressible_navier_stokes/flow_past_cylinder/include/grid.h
  include/exadg/grid/enum_types.cpp
  include/exadg/grid/enum_types.h
  include/exadg/grid/grid.h
  include/exadg/grid/grid_data.h
  include/exadg/grid/perform_local_refinements.h
Labels: new feature, software design

#153 Replace MappingQGeneric by MappingQ
  include/exadg/grid/grid.h
  include/exadg/postprocessor/statistics_manager.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/utilities/print_general_infos.h
  prototypes/moving_mesh.cpp
Labels: deal.II update

#157 fix bug introduced in PR #147
  include/exadg/grid/grid.h
Labels: bugfix

#156 Remove option IncNS::Parameters::store_previous_boundary_values = false
  applications/fluid_structure_interaction/bending_wall/application.h
  applications/fluid_structure_interaction/cylinder_with_flag/application.h
  applications/fluid_structure_interaction/pressure_wave/application.h
  applications/fluid_structure_interaction/template/application.h
  applications/incompressible_flow_with_transport/differentially_heated_cavity/application.h
  applications/incompressible_flow_with_transport/mantle_convection/application.h
  applications/incompressible_flow_with_transport/rayleigh_benard/application.h
  applications/incompressible_flow_with_transport/rising_bubble/application.h
  applications/incompressible_flow_with_transport/template/application.h
  applications/incompressible_navier_stokes/backward_facing_step/application.h
  applications/incompressible_navier_stokes/beltrami/application.h
  applications/incompressible_navier_stokes/cavity/application.h
  applications/incompressible_navier_stokes/couette/application.h
  applications/incompressible_navier_stokes/fda_benchmark/application.h
  applications/incompressible_navier_stokes/flow_past_cylinder/application.h
  applications/incompressible_navier_stokes/free_stream/application.h
  applications/incompressible_navier_stokes/kelvin_helmholtz/application.h
  applications/incompressible_navier_stokes/kovasznay/application.h
  applications/incompressible_navier_stokes/orr_sommerfeld/application.h
  applications/incompressible_navier_stokes/periodic_hill/application.h
  applications/incompressible_navier_stokes/poiseuille/application.h
  applications/incompressible_navier_stokes/poiseuille/tests/parabolic_inflow.output
  applications/incompressible_navier_stokes/poiseuille/tests/parabolic_inflow_symmetry_bc.output
  applications/incompressible_navier_stokes/poiseuille/tests/periodic_bc.output
  applications/incompressible_navier_stokes/poiseuille/tests/pressure_inflow.output
  applications/incompressible_navier_stokes/shear_layer/application.h
  applications/incompressible_navier_stokes/stokes_manufactured/application.h
  applications/incompressible_navier_stokes/taylor_green_vortex/application.h
  applications/incompressible_navier_stokes/template/application.h
  applications/incompressible_navier_stokes/turbulent_channel/application.h
  applications/incompressible_navier_stokes/vortex/application.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/user_interface/boundary_descriptor.h
  include/exadg/incompressible_navier_stokes/user_interface/parameters.cpp
  include/exadg/incompressible_navier_stokes/user_interface/parameters.h
Labels: drop feature

#160 split FSI::ApplicationBase::setup() into two parts (structure and fluid/ALE)
  include/exadg/fluid_structure_interaction/user_interface/application_base.h
Labels: refactoring, FSI

#163 remove parameter store_solution
  include/exadg/fluid_structure_interaction/driver.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf.h
  include/exadg/structure/time_integration/time_int_gen_alpha.cpp
  include/exadg/structure/time_integration/time_int_gen_alpha.h
Labels: software design, FSI

#167 Applications: clarify private/public
  applications/compressible_navier_stokes/couette/application.h
  applications/compressible_navier_stokes/euler_vortex/application.h
  applications/compressible_navier_stokes/manufactured_solution/application.h
  applications/compressible_navier_stokes/poiseuille/application.h
  applications/compressible_navier_stokes/shear_flow/application.h
  applications/compressible_navier_stokes/taylor_green/application.h
  applications/compressible_navier_stokes/template/application.h
  applications/compressible_navier_stokes/turbulent_channel/application.h
  applications/convection_diffusion/boundary_layer/application.h
  applications/convection_diffusion/const_rhs/application.h
  applications/convection_diffusion/decaying_hill/application.h
  applications/convection_diffusion/deforming_hill/application.h
  applications/convection_diffusion/rotating_hill/application.h
  applications/convection_diffusion/sine_wave/application.h
  applications/convection_diffusion/template/application.h
  applications/convection_diffusion/throughput/application.h
  applications/fluid_structure_interaction/bending_wall/application.h
  applications/fluid_structure_interaction/cylinder_with_flag/application.h
  applications/fluid_structure_interaction/pressure_wave/application.h
  applications/fluid_structure_interaction/template/application.h
  applications/incompressible_flow_with_transport/differentially_heated_cavity/application.h
  applications/incompressible_flow_with_transport/mantle_convection/application.h
  applications/incompressible_flow_with_transport/rayleigh_benard/application.h
  applications/incompressible_flow_with_transport/rising_bubble/application.h
  applications/incompressible_flow_with_transport/template/application.h
  applications/incompressible_navier_stokes/backward_facing_step/application.h
  applications/incompressible_navier_stokes/beltrami/application.h
  applications/incompressible_navier_stokes/cavity/application.h
  applications/incompressible_navier_stokes/couette/application.h
  applications/incompressible_navier_stokes/fda_benchmark/application.h
  applications/incompressible_navier_stokes/fda_benchmark/application_poisson.h
  applications/incompressible_navier_stokes/flow_past_cylinder/application.h
  applications/incompressible_navier_stokes/free_stream/application.h
  applications/incompressible_navier_stokes/kelvin_helmholtz/application.h
  applications/incompressible_navier_stokes/kovasznay/application.h
  applications/incompressible_navier_stokes/orr_sommerfeld/application.h
  applications/incompressible_navier_stokes/periodic_hill/application.h
  applications/incompressible_navier_stokes/poiseuille/application.h
  applications/incompressible_navier_stokes/shear_layer/application.h
  applications/incompressible_navier_stokes/stokes_manufactured/application.h
  applications/incompressible_navier_stokes/taylor_green_vortex/application.h
  applications/incompressible_navier_stokes/template/application.h
  applications/incompressible_navier_stokes/template_precursor/application.h
  applications/incompressible_navier_stokes/throughput/application.h
  applications/incompressible_navier_stokes/turbulent_channel/application.h
  applications/incompressible_navier_stokes/vortex/application.h
  applications/poisson/gaussian/application.h
  applications/poisson/sine/application.h
  applications/poisson/slit/application.h
  applications/poisson/template/application.h
  applications/poisson/throughput/application.h
  applications/structure/bar/application.h
  applications/structure/beam/application.h
  applications/structure/can/application.h
  applications/structure/manufactured/application.h
  applications/structure/template/application.h
Labels: refactoring

#168 introduce struct OutputParameters and use it for all apps
  applications/compressible_navier_stokes/couette/application.h
  applications/compressible_navier_stokes/euler_vortex/application.h
  applications/compressible_navier_stokes/manufactured_solution/application.h
  applications/compressible_navier_stokes/poiseuille/application.h
  applications/compressible_navier_stokes/shear_flow/application.h
  applications/compressible_navier_stokes/taylor_green/application.h
  applications/compressible_navier_stokes/turbulent_channel/application.h
  applications/convection_diffusion/boundary_layer/application.h
  applications/convection_diffusion/const_rhs/application.h
  applications/convection_diffusion/decaying_hill/application.h
  applications/convection_diffusion/deforming_hill/application.h
  applications/convection_diffusion/rotating_hill/application.h
  applications/convection_diffusion/sine_wave/application.h
  applications/fluid_structure_interaction/bending_wall/application.h
  applications/fluid_structure_interaction/cylinder_with_flag/application.h
  applications/fluid_structure_interaction/pressure_wave/application.h
  applications/incompressible_flow_with_transport/differentially_heated_cavity/application.h
  applications/incompressible_flow_with_transport/mantle_convection/application.h
  applications/incompressible_flow_with_transport/rayleigh_benard/application.h
  applications/incompressible_flow_with_transport/rising_bubble/application.h
  applications/incompressible_navier_stokes/backward_facing_step/application.h
  applications/incompressible_navier_stokes/beltrami/application.h
  applications/incompressible_navier_stokes/cavity/application.h
  applications/incompressible_navier_stokes/couette/application.h
  applications/incompressible_navier_stokes/fda_benchmark/application.h
  applications/incompressible_navier_stokes/fda_benchmark/application_poisson.h
  applications/incompressible_navier_stokes/flow_past_cylinder/application.h
  applications/incompressible_navier_stokes/free_stream/application.h
  applications/incompressible_navier_stokes/kelvin_helmholtz/application.h
  applications/incompressible_navier_stokes/kovasznay/application.h
  applications/incompressible_navier_stokes/orr_sommerfeld/application.h
  applications/incompressible_navier_stokes/periodic_hill/application.h
  applications/incompressible_navier_stokes/poiseuille/application.h
  applications/incompressible_navier_stokes/shear_layer/application.h
  applications/incompressible_navier_stokes/stokes_manufactured/application.h
  applications/incompressible_navier_stokes/taylor_green_vortex/application.h
  applications/incompressible_navier_stokes/turbulent_channel/application.h
  applications/incompressible_navier_stokes/vortex/application.h
  applications/poisson/gaussian/application.h
  applications/poisson/sine/application.h
  applications/poisson/slit/application.h
  applications/structure/bar/application.h
  applications/structure/beam/application.h
  applications/structure/can/application.h
  applications/structure/manufactured/application.h
  include/exadg/compressible_navier_stokes/user_interface/application_base.h
  include/exadg/convection_diffusion/user_interface/application_base.h
  include/exadg/fluid_structure_interaction/user_interface/application_base.h
  include/exadg/incompressible_flow_with_transport/user_interface/application_base.h
  include/exadg/incompressible_navier_stokes/user_interface/application_base.h
  include/exadg/poisson/user_interface/application_base.h
  include/exadg/structure/user_interface/application_base.h
  include/exadg/utilities/output_parameters.h
Labels: refactoring

#169 Make design of FSI::ApplicationBase modular
  applications/fluid_structure_interaction/bending_wall/application.h
  applications/fluid_structure_interaction/cylinder_with_flag/application.h
  applications/fluid_structure_interaction/pressure_wave/application.h
  applications/fluid_structure_interaction/template/application.h
  include/exadg/fluid_structure_interaction/driver.cpp
  include/exadg/fluid_structure_interaction/user_interface/application_base.h
  include/exadg/postprocessor/kinetic_energy_spectrum.cpp
Labels: software design, FSI

#175 TimerTree: only print results if level <= max_level
  include/exadg/utilities/timer_tree.h
  tests/utilities/timer.cc
  tests/utilities/timer.output
Labels: enhancement

#174 make design of FSI::Driver modular
  include/exadg/fluid_structure_interaction/acceleration_schemes/linear_algebra.h
  include/exadg/fluid_structure_interaction/acceleration_schemes/parameters.h
  include/exadg/fluid_structure_interaction/acceleration_schemes/partitioned_solver.h
  include/exadg/fluid_structure_interaction/driver.cpp
  include/exadg/fluid_structure_interaction/driver.h
  include/exadg/fluid_structure_interaction/single_field_solvers/fluid.h
  include/exadg/fluid_structure_interaction/single_field_solvers/structure.h
  include/exadg/fluid_structure_interaction/solver.h
Labels: software design, FSI

#176 make usage of TimerTree robust
  include/exadg/utilities/timer_tree.h
  tests/utilities/timer.cc
  tests/utilities/timer.output
Labels: enhancement

#177 shift implementation of TimerTree to cpp file
  CMakeLists.txt
  include/exadg/utilities/timer_tree.cpp
  include/exadg/utilities/timer_tree.h
Labels: refactoring

#178 Update deal.II
  include/exadg/operators/operator_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
Labels: deal.II update
