Repository exadg/exadg, pull requests merged in 2022-03, with the labels that each got.

#181 explain how we treat constrained degrees of freedom in OperatorBase
  include/exadg/operators/operator_base.cpp
Labels: documentation, usability

#182 add comment regarding compiler flags to configure scripts
  scripts/config_dealii.sh
  scripts/supermuc-ng/config_dealii.sh
Labels: documentation, build system, usability

#185 MultigridPreconditionerBase::initialize(): use reference
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.cpp
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.h
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.h
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/poisson/preconditioners/multigrid_preconditioner.cpp
  include/exadg/poisson/preconditioners/multigrid_preconditioner.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/structure/preconditioners/multigrid_preconditioner.cpp
  include/exadg/structure/preconditioners/multigrid_preconditioner.h
  include/exadg/structure/spatial_discretization/operator.cpp
Labels: refactoring, software design

#184 Constraints for continuous Galerkin discretizations
  include/exadg/operators/operator_base.cpp
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/interface.h
  include/exadg/structure/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operator.h
  include/exadg/structure/time_integration/driver_quasi_static_problems.cpp
  include/exadg/structure/time_integration/driver_steady_problems.cpp
  include/exadg/structure/time_integration/time_int_gen_alpha.cpp
Labels: software design

#188 take DirichletCached BCs into account for multigrid setup
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operator.cpp
Labels: bugfix

#187 improve robustness of InterfaceCoupling regarding marked_vertices
  include/exadg/functions_and_boundary_conditions/interface_coupling.h
Labels: bugfix, usability

#191 Adjust mpi_type_id to new form
  include/exadg/postprocessor/kinetic_energy_spectrum.cpp
Labels: deal.II update

#193 shift implementation of FunctionCached, ContainerInterfaceData, InterfaceCoupling to cpp files
  CMakeLists.txt
  include/exadg/functions_and_boundary_conditions/function_cached.cpp
  include/exadg/functions_and_boundary_conditions/function_cached.h
  include/exadg/functions_and_boundary_conditions/interface_coupling.cpp
  include/exadg/functions_and_boundary_conditions/interface_coupling.h
Labels: C++, refactoring

#148 Add preCICE coupled FSI Solid and Fluid solvers
  .github/workflows/test_precice.yml
  CMakeLists.txt
  applications/fluid_structure_interaction/perpendicular_flap/CMakeLists.txt
  applications/fluid_structure_interaction/perpendicular_flap/application.h
  applications/fluid_structure_interaction/perpendicular_flap/fluid-exadg/input.json
  applications/fluid_structure_interaction/perpendicular_flap/precice-config.xml
  applications/fluid_structure_interaction/perpendicular_flap/solid-exadg/input.json
  applications/fluid_structure_interaction/perpendicular_flap/solver_precice.cpp
  include/exadg/fluid_structure_interaction/precice/coupling_base.h
  include/exadg/fluid_structure_interaction/precice/dof_coupling.h
  include/exadg/fluid_structure_interaction/precice/dof_tools_extension.h
  include/exadg/fluid_structure_interaction/precice/driver.h
  include/exadg/fluid_structure_interaction/precice/driver_fluid.h
  include/exadg/fluid_structure_interaction/precice/driver_solid.h
  include/exadg/fluid_structure_interaction/precice/exadg_coupling.h
  include/exadg/fluid_structure_interaction/precice/precice_adapter.h
  include/exadg/fluid_structure_interaction/precice/precice_parameters.h
  include/exadg/fluid_structure_interaction/precice/quad_coupling.h
  include/exadg/fluid_structure_interaction/precice/solver.h
  include/exadg/fluid_structure_interaction/single_field_solvers/fluid.h
  include/exadg/fluid_structure_interaction/single_field_solvers/structure.h
  include/exadg/poisson/spatial_discretization/operator.h
  include/exadg/structure/spatial_discretization/operator.h
Labels: new feature, FSI

#202 IncNS vortex problem: remove MeshType::ComplexSurfaceManifold/ComplexVolumeManifold
  applications/incompressible_navier_stokes/vortex/application.h
Labels: refactoring, deal.II update

#199 add logo to doxygen docu
  doc/doxygen/Doxyfile
  doc/logo/exadg_logo.png
  doc/logo/exadg_logo_rounded_corners.png
  doc/logo/exadg_logo_rounded_corners_small.png
  doc/logo/exadg_logo_small.png
Labels: documentation

#197 remove unused functions find_all_active_cells_around_point() and n_locally_owned_active_cells_around_point()
  include/exadg/grid/find_all_active_cells_around_point.h
Labels: refactoring

#196 script search-and-replace-all: add 'global' option to replace all occurrences
  contrib/utilities/search-and-replace-all
Labels: bugfix

#206 CompNS Taylor-Green benchnark: refine_level should be applied only once
  applications/compressible_navier_stokes/taylor_green/application.h
Labels: bugfix

#208 use const as trailing keyword
  include/exadg/fluid_structure_interaction/precice/coupling_base.h
  include/exadg/fluid_structure_interaction/precice/dof_coupling.h
  include/exadg/fluid_structure_interaction/precice/dof_tools_extension.h
  include/exadg/fluid_structure_interaction/precice/driver_solid.h
  include/exadg/fluid_structure_interaction/precice/exadg_coupling.h
  include/exadg/fluid_structure_interaction/precice/precice_adapter.h
  include/exadg/fluid_structure_interaction/precice/precice_parameters.h
  include/exadg/fluid_structure_interaction/precice/quad_coupling.h
  include/exadg/functions_and_boundary_conditions/verify_boundary_conditions.h
  include/exadg/grid/calculate_maximum_aspect_ratio.h
  include/exadg/grid/mapping_dof_vector.h
  include/exadg/grid/one_sided_cylindrical_manifold.h
  include/exadg/grid/periodic_box.h
  include/exadg/operators/integrator_flags.h
  include/exadg/operators/interior_penalty_parameter.h
  include/exadg/operators/multigrid_operator.h
  include/exadg/operators/multigrid_operator_base.h
  include/exadg/operators/operator_base.cpp
  include/exadg/operators/operator_base.h
  include/exadg/postprocessor/kinetic_energy_spectrum.cpp
  include/exadg/postprocessor/statistics_manager.cpp
  include/exadg/postprocessor/statistics_manager.h
  include/exadg/solvers_and_preconditioners/preconditioners/preconditioner_amg.h
  include/exadg/solvers_and_preconditioners/solvers/iterative_solvers_dealii_wrapper.h
  include/exadg/utilities/general_parameters.h
  include/exadg/utilities/hypercube_resolution_parameters.h
  include/exadg/utilities/resolution_parameters.h
  include/exadg/utilities/throughput_parameters.h
Labels: C++, refactoring

#210 Refactoring of InterfaceCoupling: remove setup of marked_vertices from InterfaceCoupling::setup()
  include/exadg/fluid_structure_interaction/driver.cpp
  include/exadg/functions_and_boundary_conditions/interface_coupling.cpp
  include/exadg/functions_and_boundary_conditions/interface_coupling.h
  include/exadg/grid/marked_vertices.h
  include/exadg/poisson/overset_grids/driver.cpp
Labels: refactoring, software design

#212 use range-based for-loops for cell loops
  applications/incompressible_navier_stokes/flow_past_cylinder/include/grid.h
  include/exadg/grid/calculate_characteristic_element_length.h
  include/exadg/grid/calculate_maximum_aspect_ratio.h
  include/exadg/grid/periodic_box.h
  include/exadg/incompressible_navier_stokes/postprocessor/line_plot_calculation_statistics_homogeneous.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/operators/operator_base.cpp
  include/exadg/postprocessor/statistics_manager.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_h.cpp
  include/exadg/time_integration/time_step_calculation.h
Labels: refactoring, deal.II update
