Repository exadg/exadg, pull requests merged in 2023-12, with the labels that each got.

#616 add include for deal.II/multigrid/mg_tools.h in OperatorBase
  include/exadg/operators/operator_base.cpp
Labels: C++, deal.II update

#614 Invalid coarse mappings in multigrid
  applications/poisson/sine/application.h
  include/exadg/grid/deformed_cube_manifold.h
Labels: grid, multigrid

#605 Add acoustic output generator
  CMakeLists.txt
  applications/acoustic_conservation_equations/vibrating_membrane/application.h
  include/exadg/acoustic_conservation_equations/postprocessor/output_generator.cpp
  include/exadg/acoustic_conservation_equations/postprocessor/output_generator.h
  include/exadg/acoustic_conservation_equations/postprocessor/postprocessor.cpp
  include/exadg/acoustic_conservation_equations/postprocessor/postprocessor.h
Labels: postprocessing

#627 Add Acoustic PointwiseOutputGenerator
  CMakeLists.txt
  applications/acoustic_conservation_equations/vibrating_membrane/application.h
  include/exadg/acoustic_conservation_equations/postprocessor/pointwise_output_generator.cpp
  include/exadg/acoustic_conservation_equations/postprocessor/pointwise_output_generator.h
  include/exadg/acoustic_conservation_equations/postprocessor/postprocessor.cpp
  include/exadg/acoustic_conservation_equations/postprocessor/postprocessor.h
Labels: postprocessing
