Repository exadg/exadg, pull requests merged in 2023-06, with the labels that each got.

#455 remove template Number from verify_boundary_conditions()
  include/exadg/compressible_navier_stokes/user_interface/application_base.h
  include/exadg/compressible_navier_stokes/user_interface/boundary_descriptor.h
  include/exadg/fluid_structure_interaction/user_interface/application_base.h
  include/exadg/incompressible_navier_stokes/user_interface/application_base.h
  include/exadg/incompressible_navier_stokes/user_interface/boundary_descriptor.h
Labels: C++

#464 some corrections in multigrid implementation
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_parameters.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_global_coarsening.cpp
Labels: bugfix, multigrid

#466 use <> for include
  include/exadg/utilities/throughput_parameters.h
Labels: C++

#468 Fix bug in MG c-transfer
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_c.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_c.h
Labels: bugfix

#470 remove using namespace dealii
  applications/incompressible_navier_stokes/flow_past_sphere/application.h
  applications/incompressible_navier_stokes/flow_past_sphere/include/grid.h
  prototypes/global_coarsening.cpp
  prototypes/particles.cpp
Labels: software design

#471 remove template parameter from BDF Time Integrator
  include/exadg/convection_diffusion/time_integration/time_int_bdf.cpp
  include/exadg/convection_diffusion/time_integration/time_int_bdf.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf.h
  include/exadg/time_integration/time_int_bdf_base.cpp
  include/exadg/time_integration/time_int_bdf_base.h
Labels: refactoring

#469 add time integration constants for adams methods
  CMakeLists.txt
  include/exadg/time_integration/ab_constants.cpp
  include/exadg/time_integration/ab_constants.h
  include/exadg/time_integration/am_constants.cpp
  include/exadg/time_integration/am_constants.h
  include/exadg/time_integration/bdf_constants.h
  include/exadg/time_integration/bdf_time_integration.cpp
  include/exadg/time_integration/time_int_bdf_base.h
  include/exadg/time_integration/time_integration_constants_base.h
  tests/CMakeLists.txt
  tests/time_integration/CMakeLists.txt
  tests/time_integration/ab_constants_01.cc
  tests/time_integration/ab_constants_01.output
  tests/time_integration/ab_constants_02.cc
  tests/time_integration/ab_constants_02.output
  tests/time_integration/am_constants_01.cc
  tests/time_integration/am_constants_01.output
  tests/time_integration/am_constants_02.cc
  tests/time_integration/am_constants_02.output
Labels: new feature, time integration

#474 add tests for BDF and extrapolation constants
  tests/time_integration/bdf_constants_01.cc
  tests/time_integration/bdf_constants_01.output
  tests/time_integration/bdf_constants_02.cc
  tests/time_integration/bdf_constants_02.output
  tests/time_integration/extrapolation_constants_01.cc
  tests/time_integration/extrapolation_constants_01.output
  tests/time_integration/extrapolation_constants_02.cc
  tests/time_integration/extrapolation_constants_02.output
Labels: testing, time integration

#456 Multigrid: Use more generic loop over levels
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.cpp
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.h
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.h
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.h
  include/exadg/poisson/preconditioners/multigrid_preconditioner.cpp
  include/exadg/poisson/preconditioners/multigrid_preconditioner.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/structure/preconditioners/multigrid_preconditioner.cpp
  include/exadg/structure/preconditioners/multigrid_preconditioner.h
Labels: software design, multigrid

#476 initialized mapping_degree and adapted tests
  applications/structure/manufactured/tests/2d.output
  applications/structure/manufactured/tests/3d.output
  include/exadg/structure/user_interface/parameters.cpp
Labels: bugfix

#477 shift coarse-grid Chebyshev smoother object to MGCoarseChebyshev
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.cpp
  include/exadg/poisson/preconditioners/multigrid_preconditioner.cpp
  include/exadg/solvers_and_preconditioners/multigrid/coarse_grid_solvers.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/structure/preconditioners/multigrid_preconditioner.cpp
Labels: software design, multigrid

#473 rename file for BDF constants
  CMakeLists.txt
  include/exadg/time_integration/bdf_constants.cpp
  include/exadg/time_integration/extrapolation_constants.cpp
  include/exadg/time_integration/extrapolation_constants.h
  include/exadg/time_integration/time_int_bdf_base.h
  tests/time_integration/extrapolation_constants_01.cc
  tests/time_integration/extrapolation_constants_02.cc
Labels: refactoring

#478 fix bug in multigrid preconditioner introduced in PR #477
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
Labels: bugfix

#434 fix failing Poisseuille test case
  applications/incompressible_navier_stokes/poiseuille/application.h
  applications/incompressible_navier_stokes/poiseuille/tests/parabolic_inflow.output
  applications/incompressible_navier_stokes/poiseuille/tests/parabolic_inflow_symmetry_bc.output
  applications/incompressible_navier_stokes/poiseuille/tests/periodic_bc.output
  applications/incompressible_navier_stokes/poiseuille/tests/pressure_inflow.output
Labels: testing

#480 consistently use and syntax in time integration constants
  include/exadg/time_integration/am_constants.cpp
  include/exadg/time_integration/time_integration_constants_base.h
Labels: refactoring

#458 expose data needed for pressure time derivatives
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf.h
  include/exadg/time_integration/bdf_constants.h
  include/exadg/time_integration/time_int_bdf_base.cpp
  include/exadg/time_integration/time_int_bdf_base.h
  tests/time_integration/bdf_time_derivative_01.cc
  tests/time_integration/bdf_time_derivative_01.output
Labels: multiphysics

#481 implement Chebyshev smoother in a more encapsulated way
  include/exadg/solvers_and_preconditioners/multigrid/coarse_grid_solvers.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_parameters.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/solvers_and_preconditioners/multigrid/smoothers/cg_smoother.h
  include/exadg/solvers_and_preconditioners/multigrid/smoothers/chebyshev_smoother.h
  include/exadg/solvers_and_preconditioners/multigrid/smoothers/gmres_smoother.h
  include/exadg/solvers_and_preconditioners/multigrid/smoothers/jacobi_smoother.h
Labels: software design, multigrid

#472 Use MGTransferGlobalCoarsening inside of MGTransferGlobalRefinement
  CMakeLists.txt
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer.h
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_c.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_c.h
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_global_coarsening.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_global_coarsening.h
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_global_refinement.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_global_refinement.h
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_h.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_h.h
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_p.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_p.h
Labels: multigrid

#485 rename multigrid transfer files and classes
  CMakeLists.txt
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.cpp
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.h
  include/exadg/grid/mapping_dof_vector.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_algorithm.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/solvers_and_preconditioners/multigrid/transfer.cpp
  include/exadg/solvers_and_preconditioners/multigrid/transfer.h
  include/exadg/solvers_and_preconditioners/multigrid/transfer_base.h
Labels: refactoring, multigrid

#454 Refactoring of GridTools::initialize_coarse_mappings_from_mapping_q_cache()
  include/exadg/grid/mapping_dof_vector.h
Labels: refactoring, multigrid

#491 constructor of Grid has not been called for precursor domain in solver_precursor
  include/exadg/incompressible_navier_stokes/user_interface/application_base.h
Labels: bugfix

#494 fix writing Rho_E in pointwise output of CNSE
  include/exadg/compressible_navier_stokes/postprocessor/pointwise_output_generator.cpp
Labels: bugfix

#496 Enable OperatorBase::rhs()/evaluate() for is_dg=false or evaluate_face_integrals=false
  include/exadg/operators/operator_base.cpp
Labels: bugfix, matrix-free

#497 use new enum utility functions for throughput studies
  applications/incompressible_navier_stokes/throughput/input.json
  applications/poisson/throughput/input.json
  include/exadg/compressible_navier_stokes/driver.cpp
  include/exadg/compressible_navier_stokes/driver.h
  include/exadg/compressible_navier_stokes/solver.h
  include/exadg/compressible_navier_stokes/throughput.h
  include/exadg/convection_diffusion/driver.cpp
  include/exadg/convection_diffusion/driver.h
  include/exadg/convection_diffusion/solver.h
  include/exadg/convection_diffusion/throughput.h
  include/exadg/fluid_structure_interaction/solver.h
  include/exadg/incompressible_flow_with_transport/solver.h
  include/exadg/incompressible_navier_stokes/driver.cpp
  include/exadg/incompressible_navier_stokes/driver.h
  include/exadg/incompressible_navier_stokes/solver.h
  include/exadg/incompressible_navier_stokes/solver_precursor.h
  include/exadg/incompressible_navier_stokes/throughput.h
  include/exadg/poisson/driver.cpp
  include/exadg/poisson/driver.h
  include/exadg/poisson/solver.h
  include/exadg/poisson/throughput.h
  include/exadg/structure/driver.cpp
  include/exadg/structure/driver.h
  include/exadg/structure/solver.h
  include/exadg/structure/throughput.h
  include/exadg/utilities/enum_utilities.h
  include/exadg/utilities/hypercube_resolution_parameters.h
  include/exadg/utilities/throughput_parameters.h
Labels: software design

#498 some clean up in utilities directory
  include/exadg/fluid_structure_interaction/precice/exadg_coupling.h
  include/exadg/fluid_structure_interaction/precice/precice_adapter.h
  include/exadg/functions_and_boundary_conditions/container_interface_data.h
  include/exadg/functions_and_boundary_conditions/interface_coupling.h
  include/exadg/poisson/driver.h
  include/exadg/postprocessor/pointwise_output_generator_base.h
  include/exadg/utilities/n_components_to_rank.h
  include/exadg/utilities/print_solver_results.h
  include/exadg/utilities/solver_result.h
  include/exadg/utilities/tensor_utilities.h
Labels: refactoring

#499 enable running FDA benchmark without precursor
  applications/incompressible_navier_stokes/backward_facing_step/application.h
  applications/incompressible_navier_stokes/fda_benchmark/application.h
  include/exadg/incompressible_navier_stokes/solver_precursor.h
  include/exadg/incompressible_navier_stokes/user_interface/application_base.h
Labels: bugfix

#508 refactor reinit_cell/face/boundary_face() functions in OperatorBase
  include/exadg/convection_diffusion/spatial_discretization/operators/combined_operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operators/combined_operator.h
  include/exadg/convection_diffusion/spatial_discretization/operators/convective_operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operators/convective_operator.h
  include/exadg/convection_diffusion/spatial_discretization/operators/diffusive_operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operators/diffusive_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/convective_operator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/convective_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/momentum_operator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/momentum_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/projection_operator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/projection_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/viscous_operator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/viscous_operator.h
  include/exadg/operators/operator_base.cpp
  include/exadg/operators/operator_base.h
  include/exadg/poisson/spatial_discretization/laplace_operator.cpp
  include/exadg/poisson/spatial_discretization/laplace_operator.h
  include/exadg/structure/spatial_discretization/operators/elasticity_operator_base.cpp
  include/exadg/structure/spatial_discretization/operators/elasticity_operator_base.h
  include/exadg/structure/spatial_discretization/operators/nonlinear_operator.cpp
  include/exadg/structure/spatial_discretization/operators/nonlinear_operator.h
Labels: software design, high priority, matrix-free

#509 make IntegratorCell/Face objects private in OperatorBase
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/projection_operator.cpp
  include/exadg/operators/operator_base.h
  include/exadg/poisson/spatial_discretization/laplace_operator.cpp
  include/exadg/structure/spatial_discretization/operators/nonlinear_operator.cpp
Labels: software design, matrix-free

#510 make IntegratorCell/Face objects local variables in cell/face_loop()
  include/exadg/operators/operator_base.cpp
  include/exadg/operators/operator_base.h
Labels: software design, matrix-free
