Repository exadg/exadg, pull requests merged in 2023-11, with the labels that each got.

#587 Add acoustic operator
  include/exadg/acoustic_conservation_equations/spatial_discretization/operators/operator.h
  include/exadg/acoustic_conservation_equations/spatial_discretization/operators/weak_boundary_conditions.h
  include/exadg/acoustic_conservation_equations/user_interface/boundary_descriptor.h
  include/exadg/acoustic_conservation_equations/user_interface/enum_types.h
  include/exadg/functions_and_boundary_conditions/boundary_face_integrator_base.h
Labels: new feature, multiphysics

#589 Implement additive Schwarz Preconditioner
  include/exadg/operators/multigrid_operator.h
  include/exadg/operators/multigrid_operator_base.h
  include/exadg/operators/operator_base.cpp
  include/exadg/operators/operator_base.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/user_interface/enum_types.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_parameters.h
  include/exadg/solvers_and_preconditioners/multigrid/smoothers/chebyshev_smoother.h
  include/exadg/solvers_and_preconditioners/multigrid/smoothers/jacobi_smoother.h
  include/exadg/solvers_and_preconditioners/preconditioners/additive_schwarz_preconditioner.h
Labels: preconditioning

#596 Move grid and mapping to driver for ConvDiff module
  applications/convection_diffusion/boundary_layer/application.h
  applications/convection_diffusion/const_rhs/application.h
  applications/convection_diffusion/decaying_hill/application.h
  applications/convection_diffusion/deforming_hill/application.h
  applications/convection_diffusion/rotating_hill/application.h
  applications/convection_diffusion/sine_wave/application.h
  applications/convection_diffusion/template/application.h
  applications/convection_diffusion/throughput/application.h
  include/exadg/convection_diffusion/driver.cpp
  include/exadg/convection_diffusion/driver.h
  include/exadg/convection_diffusion/user_interface/application_base.h
Labels: software design, grid

#600 optimize Jacobi preconditioner implementation
  include/exadg/solvers_and_preconditioners/preconditioners/jacobi_preconditioner.h
Labels: performance

#602 allow update of inverse mass operator and refactor block-Jacobi implementation
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/operators/inverse_mass_operator.h
  include/exadg/operators/multigrid_operator.h
  include/exadg/operators/multigrid_operator_base.h
  include/exadg/operators/operator_base.cpp
  include/exadg/operators/operator_base.h
  include/exadg/solvers_and_preconditioners/preconditioners/block_jacobi_preconditioner.h
  include/exadg/solvers_and_preconditioners/preconditioners/elementwise_preconditioners.h
  include/exadg/solvers_and_preconditioners/preconditioners/inverse_mass_preconditioner.h
Labels: ALE, preconditioning

#564 Clean up order of initialization steps in flow-transport driver
  include/exadg/incompressible_flow_with_transport/driver.cpp
Labels: refactoring, multiphysics
