Repository exadg/exadg, pull requests merged in 2023-03, with the labels that each got.

#341 add update_ghost_values in normal_flux_calculation
  include/exadg/postprocessor/normal_flux_calculation.cpp
Labels: bugfix, postprocessing

#362 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, usability

#356 Add dyadic function evaluator
  include/exadg/functions_and_boundary_conditions/evaluate_functions.h
Labels: enhancement

#342 always use construct_multigrid_hierarchy for LocalSmoothing-MG
  include/exadg/compressible_navier_stokes/user_interface/application_base.h
  include/exadg/convection_diffusion/user_interface/application_base.h
  include/exadg/fluid_structure_interaction/user_interface/application_base.h
  include/exadg/grid/grid.cpp
  include/exadg/grid/grid.h
  include/exadg/grid/grid_utilities.h
  include/exadg/incompressible_navier_stokes/user_interface/application_base.h
  include/exadg/poisson/user_interface/application_base.h
  include/exadg/structure/user_interface/application_base.h
Labels: bugfix, multigrid

#377 adjust indent-all script to use new clang-format version
  contrib/utilities/indent-all
Labels: build system, usability

#353 Generalize variable coefficients to arbitrary types
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/momentum_operator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/viscous_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/user_interface/parameters.cpp
  include/exadg/operators/variable_coefficients.h
  include/exadg/structure/material/library/st_venant_kirchhoff.cpp
  include/exadg/structure/material/library/st_venant_kirchhoff.h
  include/exadg/structure/material/material_handler.h
  include/exadg/structure/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operators/elasticity_operator_base.cpp
  include/exadg/structure/spatial_discretization/operators/elasticity_operator_base.h
Labels: enhancement

#352 Omit creating the finest level again for Fullydistributed global coarsening multigrid
  include/exadg/grid/grid_utilities.h
Labels: refactoring, performance

#369 refactor navier_stokes_calculators
  CMakeLists.txt
  include/exadg/compressible_navier_stokes/spatial_discretization/calculators.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/calculators/divergence_calculator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/calculators/divergence_calculator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/calculators/q_criterion_calculator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/calculators/q_criterion_calculator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/calculators/velocity_magnitude_calculator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/calculators/velocity_magnitude_calculator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/calculators/vorticity_calculator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/calculators/vorticity_calculator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/operators/navier_stokes_calculators.cpp
  include/exadg/operators/navier_stokes_calculators.h
Labels: refactoring

#355 Add git info of exadg
  .gitignore
  CMakeLists.txt
  EXADGConfig.cmake.in
  include/exadg/utilities/exadg_revision.h.in
  include/exadg/utilities/print_general_infos.cpp
  include/exadg/utilities/print_general_infos.h
Labels: documentation, usability

#384 Refactoring of affine constraints in OperatorBase
  include/exadg/operators/operator_base.cpp
  include/exadg/operators/operator_base.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operator.cpp
Labels: documentation, refactoring

#388 Implement imposition of hanging node constraints and periodic boundaries for CG discretizations
  include/exadg/grid/grid_utilities.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operator.h
Labels: bugfix, new feature, mesh adaptivity

#389 Enable periodic faces for global-coarsening multigrid
  applications/compressible_navier_stokes/couette/application.h
  applications/compressible_navier_stokes/manufactured_solution/application.h
  applications/compressible_navier_stokes/taylor_green/application.h
  applications/compressible_navier_stokes/turbulent_channel/application.h
  applications/convection_diffusion/throughput/application.h
  applications/incompressible_flow_with_transport/rayleigh_benard/application.h
  applications/incompressible_navier_stokes/backward_facing_step/application.h
  applications/incompressible_navier_stokes/fda_benchmark/application.h
  applications/incompressible_navier_stokes/fda_benchmark/application_poisson.h
  applications/incompressible_navier_stokes/flow_past_cylinder/application.h
  applications/incompressible_navier_stokes/flow_past_sphere/application.h
  applications/incompressible_navier_stokes/kelvin_helmholtz/application.h
  applications/incompressible_navier_stokes/orr_sommerfeld/application.h
  applications/incompressible_navier_stokes/periodic_hill/application.h
  applications/incompressible_navier_stokes/poiseuille/application.h
  applications/incompressible_navier_stokes/shear_layer/application.h
  applications/incompressible_navier_stokes/taylor_green_vortex/application.h
  applications/incompressible_navier_stokes/throughput/application.h
  applications/incompressible_navier_stokes/turbulent_channel/application.h
  applications/incompressible_navier_stokes/vortex_periodic_bc/application.h
  applications/poisson/sine/application.h
  applications/poisson/throughput/application.h
  applications/structure/bar/application.h
  include/exadg/compressible_navier_stokes/user_interface/application_base.h
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.cpp
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.h
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/convection_diffusion/user_interface/application_base.h
  include/exadg/fluid_structure_interaction/user_interface/application_base.h
  include/exadg/functions_and_boundary_conditions/verify_boundary_conditions.h
  include/exadg/grid/grid.cpp
  include/exadg/grid/grid.h
  include/exadg/grid/grid_utilities.h
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.h
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/user_interface/application_base.h
  include/exadg/poisson/preconditioners/multigrid_preconditioner.cpp
  include/exadg/poisson/preconditioners/multigrid_preconditioner.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/user_interface/application_base.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/structure/preconditioners/multigrid_preconditioner.cpp
  include/exadg/structure/preconditioners/multigrid_preconditioner.h
  include/exadg/structure/spatial_discretization/operator.cpp
  include/exadg/structure/user_interface/application_base.h
Labels: enhancement, multigrid

#396 combine the two update() functions in TimeIntegratorConstantsBase
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_pressure_correction.cpp
  include/exadg/time_integration/time_int_bdf_base.cpp
  include/exadg/time_integration/time_integration_constants_base.h
Labels: refactoring, time integration

#378 Incorporate non-hypercube elements and every triangulation type in categorazation.h
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.cpp
  include/exadg/matrix_free/categorization.h
  include/exadg/poisson/preconditioners/multigrid_preconditioner.cpp
Labels: simplex
