Repository exadg/exadg, pull requests merged in 2023-02, with the labels that each got.

#314 Change interface of linear solvers
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/operators/operator_base.cpp
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/solvers_and_preconditioners/multigrid/coarse_grid_solvers.h
  include/exadg/solvers_and_preconditioners/newton/newton_solver.h
  include/exadg/solvers_and_preconditioners/solvers/iterative_solvers_dealii_wrapper.h
  include/exadg/solvers_and_preconditioners/solvers/wrapper_elementwise_solvers.h
  include/exadg/structure/spatial_discretization/operator.cpp
Labels: refactoring, software design

#335 remove n_subdivisions_1d_hypercube from GridData
  applications/compressible_navier_stokes/couette/tests/couette.output
  applications/compressible_navier_stokes/euler_vortex/tests/euler_vortex.output
  applications/compressible_navier_stokes/manufactured_solution/tests/manufactured.output
  applications/compressible_navier_stokes/shear_flow/tests/shear_flow.output
  applications/compressible_navier_stokes/taylor_green/application.h
  applications/convection_diffusion/boundary_layer/tests/p_convergence.output
  applications/convection_diffusion/decaying_hill/tests/diffusive_implicit_time_int.output
  applications/convection_diffusion/deforming_hill/tests/convective_explicit_time_int.output
  applications/convection_diffusion/rotating_hill/tests/convective_implicit_time_int.output
  applications/convection_diffusion/sine_wave/tests/explicit_time_int.output
  applications/convection_diffusion/throughput/application.h
  applications/incompressible_navier_stokes/couette/tests/steady_navier_stokes_coupled.output
  applications/incompressible_navier_stokes/free_stream/tests/coupled_bdf2_moving_mesh.output
  applications/incompressible_navier_stokes/free_stream/tests/coupled_bdf2_static_mesh.output
  applications/incompressible_navier_stokes/poiseuille/tests/parabolic_inflow.output
  applications/incompressible_navier_stokes/poiseuille/tests/parabolic_inflow_symmetry_bc.output
  applications/incompressible_navier_stokes/poiseuille/tests/periodic_bc.output
  applications/incompressible_navier_stokes/poiseuille/tests/pressure_inflow.output
  applications/incompressible_navier_stokes/throughput/application.h
  applications/poisson/gaussian/application.h
  applications/poisson/gaussian/tests/gaussian.output
  applications/poisson/sine/application.h
  applications/poisson/sine/tests/cartesian.output
  applications/poisson/sine/tests/curvilinear.output
  applications/poisson/throughput/application.h
  applications/structure/manufactured/application.h
  applications/structure/manufactured/tests/2d.output
  applications/structure/manufactured/tests/3d.output
  include/exadg/compressible_navier_stokes/user_interface/application_base.h
  include/exadg/convection_diffusion/user_interface/application_base.h
  include/exadg/grid/grid_data.h
  include/exadg/incompressible_navier_stokes/user_interface/application_base.h
  include/exadg/poisson/user_interface/application_base.h
  include/exadg/structure/user_interface/application_base.h
Labels: grid

#333 implement normal-flux calculation for scalar-transport / Poisson type problems
  CMakeLists.txt
  applications/incompressible_navier_stokes/fda_benchmark/application_poisson.h
  applications/poisson/gaussian/application.h
  applications/poisson/overset_grids/application.h
  applications/poisson/sine/application.h
  applications/poisson/slit/application.h
  applications/poisson/template/application.h
  applications/poisson/throughput/application.h
  include/exadg/convection_diffusion/driver.cpp
  include/exadg/convection_diffusion/postprocessor/postprocessor.cpp
  include/exadg/convection_diffusion/postprocessor/postprocessor.h
  include/exadg/convection_diffusion/postprocessor/postprocessor_base.h
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operator.h
  include/exadg/incompressible_flow_with_transport/driver.cpp
  include/exadg/poisson/postprocessor/postprocessor.cpp
  include/exadg/poisson/postprocessor/postprocessor.h
  include/exadg/poisson/postprocessor/postprocessor_base.h
  include/exadg/poisson/solver_poisson.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/spatial_discretization/operator.h
  include/exadg/poisson/user_interface/application_base.h
  include/exadg/postprocessor/normal_flux_calculation.cpp
  include/exadg/postprocessor/normal_flux_calculation.h
Labels: new feature, postprocessing

#336 Postprocess shear rate
  CMakeLists.txt
  applications/compressible_navier_stokes/poiseuille/application.h
  applications/incompressible_navier_stokes/poiseuille/application.h
  contrib/utilities/indent-all
  include/exadg/compressible_navier_stokes/postprocessor/output_generator.h
  include/exadg/compressible_navier_stokes/postprocessor/postprocessor.cpp
  include/exadg/compressible_navier_stokes/postprocessor/postprocessor.h
  include/exadg/compressible_navier_stokes/spatial_discretization/calculators.h
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.cpp
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.h
  include/exadg/incompressible_navier_stokes/postprocessor/output_generator.h
  include/exadg/incompressible_navier_stokes/postprocessor/postprocessor.cpp
  include/exadg/incompressible_navier_stokes/postprocessor/postprocessor.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/operators/navier_stokes_calculators.cpp
  include/exadg/operators/navier_stokes_calculators.h
Labels: postprocessing

#345 enable AMG preconditioner for Poisson module
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/user_interface/enum_types.cpp
  include/exadg/poisson/user_interface/enum_types.h
Labels: enhancement, multigrid
