Repository exadg/exadg, pull requests merged in 2023-05, with the labels that each got.

#380 Implement inverse mass operator for DG + simplex elements
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/project_velocity.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/user_interface/parameters.cpp
  include/exadg/incompressible_navier_stokes/user_interface/parameters.h
  include/exadg/operators/inverse_mass_operator.h
  include/exadg/operators/mass_operator.cpp
  include/exadg/operators/operator_base.cpp
  include/exadg/solvers_and_preconditioners/preconditioners/inverse_mass_preconditioner.h
Labels: simplex

#420 remove function IncNS::Parameters::linear_problem_has_to_be_solved()
  include/exadg/incompressible_navier_stokes/time_integration/driver_steady_problems.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_coupled_solver.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/user_interface/parameters.cpp
  include/exadg/incompressible_navier_stokes/user_interface/parameters.h
Labels: refactoring, software design

#425 IncNS::SpatialOperatorBase: use member function get_mapping()
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
Labels: software design

#423 redesign SpatialOperator::move_grid_and_update_dependent_data_structures()
  include/exadg/convection_diffusion/driver.cpp
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.cpp
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.h
  include/exadg/convection_diffusion/spatial_discretization/interface.h
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operator.h
  include/exadg/convection_diffusion/time_integration/time_int_bdf.cpp
  include/exadg/fluid_structure_interaction/single_field_solvers/fluid.h
  include/exadg/incompressible_flow_with_transport/driver.cpp
  include/exadg/incompressible_navier_stokes/driver.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.h
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_pressure_correction.cpp
Labels: refactoring, ALE

#417 Provide configure script and installation description for HDF5
  scripts/config_hdf5.sh
Labels: build system

#351 Simplex support for incompressible Navier-Stokes
  applications/incompressible_navier_stokes/flow_past_cylinder/application.h
  applications/incompressible_navier_stokes/flow_past_cylinder/include/grid.h
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/incompressible_navier_stokes/user_interface/parameters.cpp
Labels: new feature, simplex

#435 introduce a utility function for subdivided hyper rectangle
  applications/incompressible_navier_stokes/flow_past_cylinder/include/grid.h
  include/exadg/grid/hyper_rectangle.h
Labels: refactoring, simplex

#418 fix config error for trilinos by setting a GlobalOrdinal type
  scripts/config_trilinos.sh
Labels: bugfix, build system

#433 add plotting in interface_coupling before assertion
  include/exadg/compressible_navier_stokes/postprocessor/output_generator.cpp
  include/exadg/functions_and_boundary_conditions/interface_coupling.cpp
  include/exadg/grid/mapping_dof_vector.h
  include/exadg/incompressible_navier_stokes/postprocessor/output_generator.cpp
  include/exadg/postprocessor/write_output.h
Labels: multiphysics, postprocessing

#442 Remove FunctionCached
  CMakeLists.txt
  applications/fluid_structure_interaction/bending_wall/application.h
  applications/fluid_structure_interaction/cylinder_with_flag/application.h
  applications/fluid_structure_interaction/perpendicular_flap/application.h
  applications/fluid_structure_interaction/pressure_wave/application.h
  applications/poisson/overset_grids/application.h
  include/exadg/convection_diffusion/user_interface/boundary_descriptor.h
  include/exadg/fluid_structure_interaction/driver.cpp
  include/exadg/fluid_structure_interaction/precice/driver_fluid.h
  include/exadg/fluid_structure_interaction/precice/driver_solid.h
  include/exadg/functions_and_boundary_conditions/container_interface_data.h
  include/exadg/functions_and_boundary_conditions/evaluate_functions.h
  include/exadg/functions_and_boundary_conditions/function_cached.cpp
  include/exadg/functions_and_boundary_conditions/function_cached.h
  include/exadg/grid/marked_vertices.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/weak_boundary_conditions.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/user_interface/boundary_descriptor.h
  include/exadg/poisson/spatial_discretization/laplace_operator.cpp
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/spatial_discretization/weak_boundary_conditions.h
  include/exadg/poisson/user_interface/boundary_descriptor.h
  include/exadg/structure/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operators/boundary_conditions.h
  include/exadg/structure/spatial_discretization/operators/elasticity_operator_base.cpp
  include/exadg/structure/user_interface/boundary_descriptor.h
Labels: refactoring, multiphysics

#444 use Grid class in interface of MultigridPreconditioner::initialize()
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.cpp
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.h
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.h
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/poisson/preconditioners/multigrid_preconditioner.cpp
  include/exadg/poisson/preconditioners/multigrid_preconditioner.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/structure/preconditioners/multigrid_preconditioner.cpp
  include/exadg/structure/preconditioners/multigrid_preconditioner.h
  include/exadg/structure/spatial_discretization/operator.cpp
Labels: refactoring, multigrid

#448 Make access to MultigridPreconditionerBase::n_levels safe
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.cpp
  include/exadg/poisson/preconditioners/multigrid_preconditioner.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/structure/preconditioners/multigrid_preconditioner.cpp
Labels: software design

#451 remove last entry of vector coarse_triangulations/coarse_mappings
  include/exadg/grid/grid.h
  include/exadg/grid/grid_utilities.h
  include/exadg/grid/mapping_dof_vector.h
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
Labels: grid, multigrid
