Repository exadg/exadg, pull requests merged in 2023-07, with the labels that each got.

#512 slightly refactor throughput studies for Poisson module
  applications/poisson/throughput/input.json
  include/exadg/poisson/driver.cpp
  include/exadg/poisson/driver.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/spatial_discretization/operator.h
Labels: refactoring

#511 slightly refactor throughput studies for Structure module
  applications/structure/manufactured/throughput.json
  include/exadg/structure/driver.cpp
  include/exadg/structure/driver.h
  include/exadg/structure/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operator.h
Labels: refactoring

#506 Enable hanging nodes for continuous Galerkin discretizations
  applications/structure/bar/application.h
  applications/structure/beam/application.h
  applications/structure/can/application.h
  applications/structure/manufactured/application.h
  include/exadg/convection_diffusion/spatial_discretization/operators/combined_operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operators/combined_operator.h
  include/exadg/convection_diffusion/spatial_discretization/operators/convective_operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operators/convective_operator.h
  include/exadg/convection_diffusion/spatial_discretization/operators/diffusive_operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operators/diffusive_operator.h
  include/exadg/grid/mapping_deformation_structure.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/convective_operator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/convective_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/momentum_operator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/momentum_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/projection_operator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/projection_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/viscous_operator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/viscous_operator.h
  include/exadg/operators/constraints.h
  include/exadg/operators/operator_base.cpp
  include/exadg/operators/operator_base.h
  include/exadg/poisson/spatial_discretization/laplace_operator.cpp
  include/exadg/poisson/spatial_discretization/laplace_operator.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/spatial_discretization/operator.h
  include/exadg/postprocessor/normal_flux_calculation.cpp
  include/exadg/structure/preconditioners/multigrid_preconditioner.cpp
  include/exadg/structure/preconditioners/multigrid_preconditioner.h
  include/exadg/structure/spatial_discretization/interface.h
  include/exadg/structure/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operator.h
  include/exadg/structure/spatial_discretization/operators/elasticity_operator_base.cpp
  include/exadg/structure/spatial_discretization/operators/elasticity_operator_base.h
  include/exadg/structure/spatial_discretization/operators/mass_operator.h
  include/exadg/structure/spatial_discretization/operators/nonlinear_operator.cpp
  include/exadg/structure/spatial_discretization/operators/nonlinear_operator.h
  include/exadg/structure/time_integration/driver_steady_problems.cpp
  include/exadg/structure/time_integration/time_int_gen_alpha.cpp
  include/exadg/structure/user_interface/boundary_descriptor.h
  include/exadg/structure/user_interface/field_functions.h
Labels: enhancement, mesh adaptivity

#503 make ApplicationBasePrecursor independent of ApplicationBase
  CMakeLists.txt
  applications/incompressible_navier_stokes/backward_facing_step/CMakeLists.txt
  applications/incompressible_navier_stokes/backward_facing_step/application.h
  applications/incompressible_navier_stokes/backward_facing_step/include/functions.h
  applications/incompressible_navier_stokes/backward_facing_step/input.json
  applications/incompressible_navier_stokes/backward_facing_step/solver.cpp
  applications/incompressible_navier_stokes/fda_benchmark/CMakeLists.txt
  applications/incompressible_navier_stokes/fda_benchmark/application.h
  applications/incompressible_navier_stokes/fda_benchmark/include/functions.h
  applications/incompressible_navier_stokes/fda_benchmark/include/postprocessor.h
  applications/incompressible_navier_stokes/fda_benchmark/input.json
  applications/incompressible_navier_stokes/fda_benchmark/input_precursor.json
  applications/incompressible_navier_stokes/fda_benchmark/solver.cpp
  applications/incompressible_navier_stokes/template_precursor/CMakeLists.txt
  applications/incompressible_navier_stokes/template_precursor/application.h
  applications/incompressible_navier_stokes/template_precursor/input.json
  applications/incompressible_navier_stokes/template_precursor/solver.cpp
  include/exadg/incompressible_navier_stokes/driver_precursor.cpp
  include/exadg/incompressible_navier_stokes/driver_precursor.h
  include/exadg/incompressible_navier_stokes/precursor/driver.cpp
  include/exadg/incompressible_navier_stokes/precursor/driver.h
  include/exadg/incompressible_navier_stokes/precursor/solver.h
  include/exadg/incompressible_navier_stokes/precursor/user_interface/application_base.h
  include/exadg/incompressible_navier_stokes/precursor/user_interface/declare_get_application.h
  include/exadg/incompressible_navier_stokes/precursor/user_interface/implement_get_application.h
  include/exadg/incompressible_navier_stokes/user_interface/application_base.h
  include/exadg/incompressible_navier_stokes/user_interface/implement_get_application_precursor.h
Labels: software design

#504 make ApplicationOversetGridsBase independent of ApplicationBase
  applications/poisson/overset_grids/application.h
  applications/poisson/overset_grids/input.json
  include/exadg/poisson/driver.h
  include/exadg/poisson/overset_grids/driver.cpp
  include/exadg/poisson/overset_grids/driver.h
  include/exadg/poisson/overset_grids/solver.h
  include/exadg/poisson/overset_grids/user_interface/application_base.h
  include/exadg/poisson/overset_grids/user_interface/declare_get_application.h
  include/exadg/poisson/overset_grids/user_interface/implement_get_application.h
  include/exadg/poisson/solver_poisson.h
  include/exadg/poisson/user_interface/application_base.h
Labels: software design

#505 Make FTI::ApplicationBase independent of IncNS::ApplicationBase
  applications/incompressible_flow_with_transport/differentially_heated_cavity/application.h
  applications/incompressible_flow_with_transport/differentially_heated_cavity/input.json
  applications/incompressible_flow_with_transport/mantle_convection/application.h
  applications/incompressible_flow_with_transport/mantle_convection/input.json
  applications/incompressible_flow_with_transport/rayleigh_benard/application.h
  applications/incompressible_flow_with_transport/rayleigh_benard/input.json
  applications/incompressible_flow_with_transport/rising_bubble/application.h
  applications/incompressible_flow_with_transport/rising_bubble/input.json
  applications/incompressible_flow_with_transport/template/application.h
  applications/incompressible_flow_with_transport/template/input.json
  include/exadg/incompressible_flow_with_transport/driver.cpp
  include/exadg/incompressible_flow_with_transport/user_interface/application_base.h
  include/exadg/incompressible_navier_stokes/user_interface/application_base.h
Labels: software design

#518 Replace set_zero_mean_value by subtract_mean_value
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_pressure_correction.cpp
  include/exadg/solvers_and_preconditioners/multigrid/coarse_grid_solvers.h
  include/exadg/solvers_and_preconditioners/utilities/compute_eigenvalues.h
Labels: deal.II update

#516 Structure: Fix 'can' application
  applications/structure/can/application.h
Labels: bugfix

#513 introduce utility function for creation of dealii::FiniteElement
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.cpp
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.h
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.cpp
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.h
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/operators/finite_element.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.h
  include/exadg/structure/preconditioners/multigrid_preconditioner.cpp
  include/exadg/structure/preconditioners/multigrid_preconditioner.h
  include/exadg/structure/spatial_discretization/operator.cpp
Labels: software design

#520 introduce utility function for creation of quadrature rule
  applications/compressible_navier_stokes/couette/tests/couette.output
  applications/compressible_navier_stokes/euler_vortex/tests/euler_vortex.output
  applications/compressible_navier_stokes/manufactured_solution/tests/manufactured.output
  applications/compressible_navier_stokes/shear_flow/tests/shear_flow.output
  include/exadg/compressible_navier_stokes/spatial_discretization/kernels_and_operators.h
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.cpp
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.h
  include/exadg/compressible_navier_stokes/user_interface/application_base.h
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.cpp
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operators/diffusive_operator.h
  include/exadg/convection_diffusion/user_interface/application_base.h
  include/exadg/fluid_structure_interaction/user_interface/application_base.h
  include/exadg/grid/grid_data.h
  include/exadg/grid/grid_utilities.h
  include/exadg/grid/mapping_deformation_function.h
  include/exadg/grid/mapping_dof_vector.h
  include/exadg/incompressible_navier_stokes/postprocessor/line_plot_calculation_statistics_homogeneous.cpp
  include/exadg/incompressible_navier_stokes/postprocessor/line_plot_calculation_statistics_homogeneous.h
  include/exadg/incompressible_navier_stokes/postprocessor/output_generator.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/viscous_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/turbulence_model.cpp
  include/exadg/operators/quadrature.h
  include/exadg/poisson/preconditioners/multigrid_preconditioner.cpp
  include/exadg/poisson/spatial_discretization/laplace_operator.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/postprocessor/error_calculation.cpp
  include/exadg/postprocessor/statistics_manager.cpp
  include/exadg/structure/preconditioners/multigrid_preconditioner.cpp
  include/exadg/structure/spatial_discretization/operator.cpp
Labels: software design, simplex

#527 refactoring of resolution parameters
  applications/incompressible_navier_stokes/fda_benchmark/application.h
  include/exadg/compressible_navier_stokes/driver.cpp
  include/exadg/compressible_navier_stokes/solver.h
  include/exadg/compressible_navier_stokes/throughput.h
  include/exadg/convection_diffusion/driver.cpp
  include/exadg/convection_diffusion/solver.h
  include/exadg/convection_diffusion/throughput.h
  include/exadg/fluid_structure_interaction/user_interface/application_base.h
  include/exadg/incompressible_flow_with_transport/solver.h
  include/exadg/incompressible_flow_with_transport/user_interface/application_base.h
  include/exadg/incompressible_navier_stokes/driver.cpp
  include/exadg/incompressible_navier_stokes/precursor/solver.h
  include/exadg/incompressible_navier_stokes/precursor/user_interface/application_base.h
  include/exadg/incompressible_navier_stokes/solver.h
  include/exadg/incompressible_navier_stokes/throughput.h
  include/exadg/incompressible_navier_stokes/user_interface/application_base.h
  include/exadg/operators/hypercube_resolution_parameters.h
  include/exadg/operators/resolution_parameters.h
  include/exadg/operators/throughput_parameters.h
  include/exadg/poisson/driver.cpp
  include/exadg/poisson/overset_grids/driver.cpp
  include/exadg/poisson/overset_grids/solver.h
  include/exadg/poisson/overset_grids/user_interface/application_base.h
  include/exadg/poisson/solver.h
  include/exadg/poisson/throughput.h
  include/exadg/poisson/user_interface/application_base.h
  include/exadg/structure/driver.cpp
  include/exadg/structure/solver.h
  include/exadg/structure/throughput.h
  include/exadg/time_integration/resolution_parameters.h
Labels: refactoring

#523 remove namespace GridUtilities for free function get_element_type()
  include/exadg/compressible_navier_stokes/spatial_discretization/kernels_and_operators.h
  include/exadg/convection_diffusion/preconditioners/multigrid_preconditioner.cpp
  include/exadg/convection_diffusion/spatial_discretization/operators/diffusive_operator.h
  include/exadg/grid/grid_data.h
  include/exadg/grid/mapping_deformation_function.h
  include/exadg/grid/mapping_dof_vector.h
  include/exadg/incompressible_navier_stokes/postprocessor/line_plot_calculation_statistics_homogeneous.cpp
  include/exadg/incompressible_navier_stokes/postprocessor/output_generator.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_momentum.cpp
  include/exadg/incompressible_navier_stokes/preconditioners/multigrid_preconditioner_projection.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/viscous_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/turbulence_model.cpp
  include/exadg/poisson/preconditioners/multigrid_preconditioner.cpp
  include/exadg/poisson/spatial_discretization/laplace_operator.h
  include/exadg/postprocessor/error_calculation.cpp
  include/exadg/postprocessor/statistics_manager.cpp
  include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp
  include/exadg/structure/preconditioners/multigrid_preconditioner.cpp
Labels: refactoring
