Repository exadg/exadg, pull requests merged in 2023-08, with the labels that each got.

#533 shift lazy_ptr.h from operators to utilities
  include/exadg/operators/operator_base.h
  include/exadg/utilities/lazy_ptr.h
Labels: refactoring

#538 fix bug in create_triangulation(): create triangulation before using it
  include/exadg/grid/grid_utilities.h
Labels: bugfix

#532 avoid logic `if(abc == false) continue;`
  include/exadg/operators/solution_interpolation_between_triangulations.h
Labels: software design

#534 Enable throughput studies with automatic mesh refinement for simplices
  applications/compressible_navier_stokes/taylor_green/throughput.json
  applications/convection_diffusion/throughput/input.json
  applications/incompressible_navier_stokes/throughput/input.json
  applications/poisson/gaussian/input.json
  applications/poisson/gaussian/tests/gaussian.json
  applications/poisson/sine/input.json
  applications/poisson/sine/tests/cartesian.json
  applications/poisson/sine/tests/curvilinear.json
  applications/poisson/slit/input.json
  applications/poisson/template/input.json
  applications/poisson/throughput/application.h
  applications/poisson/throughput/input.json
  applications/structure/manufactured/throughput.json
  include/exadg/compressible_navier_stokes/driver.h
  include/exadg/compressible_navier_stokes/throughput.h
  include/exadg/convection_diffusion/driver.h
  include/exadg/convection_diffusion/throughput.h
  include/exadg/grid/grid_utilities.h
  include/exadg/incompressible_navier_stokes/driver.h
  include/exadg/incompressible_navier_stokes/throughput.h
  include/exadg/operators/finite_element.h
  include/exadg/operators/hypercube_resolution_parameters.h
  include/exadg/poisson/driver.h
  include/exadg/poisson/solver.h
  include/exadg/poisson/throughput.h
  include/exadg/poisson/user_interface/application_base.h
  include/exadg/structure/driver.h
  include/exadg/structure/throughput.h
Labels: simplex

#540 fix bug in GridUtilities
  applications/convection_diffusion/boundary_layer/application.h
  applications/convection_diffusion/const_rhs/application.h
  applications/convection_diffusion/decaying_hill/application.h
  applications/convection_diffusion/deforming_hill/application.h
  applications/convection_diffusion/rotating_hill/application.h
  applications/convection_diffusion/sine_wave/application.h
  applications/convection_diffusion/template/application.h
  applications/convection_diffusion/throughput/application.h
  applications/fluid_structure_interaction/bending_wall/application.h
  applications/fluid_structure_interaction/cylinder_with_flag/application.h
  applications/fluid_structure_interaction/perpendicular_flap/application.h
  applications/fluid_structure_interaction/pressure_wave/application.h
  applications/fluid_structure_interaction/template/application.h
  applications/incompressible_flow_with_transport/differentially_heated_cavity/application.h
  applications/incompressible_flow_with_transport/mantle_convection/application.h
  applications/incompressible_flow_with_transport/rayleigh_benard/application.h
  applications/incompressible_flow_with_transport/rising_bubble/application.h
  applications/incompressible_flow_with_transport/template/application.h
  applications/incompressible_navier_stokes/backward_facing_step/application.h
  applications/incompressible_navier_stokes/beltrami/application.h
  applications/incompressible_navier_stokes/cavity/application.h
  applications/incompressible_navier_stokes/couette/application.h
  applications/incompressible_navier_stokes/fda_benchmark/application.h
  applications/incompressible_navier_stokes/fda_benchmark/application_poisson.h
  applications/incompressible_navier_stokes/flow_past_cylinder/application.h
  applications/incompressible_navier_stokes/flow_past_sphere/application.h
  applications/incompressible_navier_stokes/free_stream/application.h
  applications/incompressible_navier_stokes/kelvin_helmholtz/application.h
  applications/incompressible_navier_stokes/kovasznay/application.h
  applications/incompressible_navier_stokes/navier_stokes_manufactured/application.h
  applications/incompressible_navier_stokes/orr_sommerfeld/application.h
  applications/incompressible_navier_stokes/periodic_hill/application.h
  applications/incompressible_navier_stokes/poiseuille/application.h
  applications/incompressible_navier_stokes/shear_layer/application.h
  applications/incompressible_navier_stokes/stokes_manufactured/application.h
  applications/incompressible_navier_stokes/taylor_green_vortex/application.h
  applications/incompressible_navier_stokes/template/application.h
  applications/incompressible_navier_stokes/template_precursor/application.h
  applications/incompressible_navier_stokes/throughput/application.h
  applications/incompressible_navier_stokes/turbulent_channel/application.h
  applications/incompressible_navier_stokes/vortex/application.h
  applications/incompressible_navier_stokes/vortex_periodic_bc/application.h
  applications/poisson/gaussian/application.h
  applications/poisson/overset_grids/application.h
  applications/poisson/sine/application.h
  applications/poisson/slit/application.h
  applications/poisson/template/application.h
  applications/poisson/throughput/application.h
  applications/structure/bar/application.h
  applications/structure/beam/application.h
  applications/structure/can/application.h
  applications/structure/manufactured/application.h
  applications/structure/template/application.h
  include/exadg/grid/grid_utilities.h
Labels: bugfix, simplex

#536 simplify affine_constraints setup in Poisson and Structure module
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operator.cpp
Labels: software design

#537 Comment and refactor structure material
  include/exadg/structure/material/library/st_venant_kirchhoff.cpp
  include/exadg/structure/material/library/st_venant_kirchhoff.h
  include/exadg/structure/material/material.h
  include/exadg/structure/material/material_handler.h
  include/exadg/structure/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operators/elasticity_operator_base.cpp
  include/exadg/structure/spatial_discretization/operators/elasticity_operator_base.h
  include/exadg/structure/spatial_discretization/operators/linear_operator.cpp
  include/exadg/structure/spatial_discretization/operators/nonlinear_operator.cpp
Labels: refactoring, structure

#525 Simplex updates
  applications/fluid_structure_interaction/cylinder_with_flag/application.h
  applications/fluid_structure_interaction/pressure_wave/application.h
  applications/incompressible_navier_stokes/fda_benchmark/include/grid.h
  applications/incompressible_navier_stokes/flow_past_cylinder/include/grid.h
  include/exadg/grid/calculate_characteristic_element_length.h
  include/exadg/grid/calculate_maximum_aspect_ratio.h
  include/exadg/grid/grid_utilities.h
  include/exadg/grid/mapping_deformation_base.h
  include/exadg/grid/mapping_deformation_function.h
  include/exadg/grid/mapping_deformation_poisson.h
  include/exadg/grid/mapping_deformation_structure.h
  include/exadg/grid/marked_vertices.h
  include/exadg/grid/one_sided_cylindrical_manifold.h
  include/exadg/incompressible_navier_stokes/postprocessor/line_plot_calculation_statistics.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/incompressible_navier_stokes/time_integration/time_int_bdf_coupled_solver.cpp
  include/exadg/operators/mass_operator.cpp
  include/exadg/operators/quadrature.h
  include/exadg/operators/solution_interpolation_between_triangulations.h
  include/exadg/poisson/postprocessor/postprocessor_base.h
  include/exadg/postprocessor/kinetic_energy_spectrum.cpp
  include/exadg/postprocessor/kinetic_energy_spectrum.h
  include/exadg/postprocessor/mirror_dof_vector_taylor_green.h
  include/exadg/postprocessor/solution_interpolation.h
  include/exadg/postprocessor/spectral_analysis/interpolation.h
  include/exadg/postprocessor/statistics_manager.cpp
Labels: simplex

#550 remove naive version of aspect ratio computation
  include/exadg/grid/calculate_characteristic_element_length.h
  include/exadg/grid/calculate_maximum_aspect_ratio.h
  include/exadg/poisson/user_interface/application_base.h
Labels: drop feature, grid

#558 rename function distribute_dofs()
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.cpp
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.h
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/spatial_discretization/operator.h
  include/exadg/structure/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operator.h
Labels: refactoring

#556 change order of function calls in IncNS::SpatialOperatorBase initialization routines
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/operators/operator_base.h
Labels: refactoring

#563 introduce a second Operator::setup() function for easy use in applications
  include/exadg/compressible_navier_stokes/driver.cpp
  include/exadg/compressible_navier_stokes/driver.h
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.cpp
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.h
  include/exadg/convection_diffusion/driver.cpp
  include/exadg/convection_diffusion/driver.h
  include/exadg/convection_diffusion/spatial_discretization/interface.h
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/convection_diffusion/spatial_discretization/operator.h
  include/exadg/fluid_structure_interaction/precice/coupling_base.h
  include/exadg/fluid_structure_interaction/precice/dof_coupling.h
  include/exadg/fluid_structure_interaction/precice/driver_fluid.h
  include/exadg/fluid_structure_interaction/precice/driver_solid.h
  include/exadg/fluid_structure_interaction/precice/exadg_coupling.h
  include/exadg/fluid_structure_interaction/precice/precice_adapter.h
  include/exadg/fluid_structure_interaction/precice/quad_coupling.h
  include/exadg/fluid_structure_interaction/single_field_solvers/fluid.h
  include/exadg/grid/mapping_deformation_poisson.h
  include/exadg/grid/mapping_deformation_structure.h
  include/exadg/incompressible_flow_with_transport/driver.cpp
  include/exadg/incompressible_navier_stokes/driver.cpp
  include/exadg/incompressible_navier_stokes/driver.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_projection_methods.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/poisson/driver.h
  include/exadg/poisson/overset_grids/driver.h
  include/exadg/poisson/postprocessor/postprocessor.cpp
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/spatial_discretization/operator.h
  include/exadg/structure/driver.cpp
  include/exadg/structure/driver.h
  include/exadg/structure/spatial_discretization/operator.cpp
  include/exadg/structure/spatial_discretization/operator.h
Labels: software design, usability

#565 Extend div- and conti-penalty parameters to ElementType::Simplex
  include/exadg/grid/calculate_characteristic_element_length.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/continuity_penalty_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operators/divergence_penalty_operator.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
Labels: simplex

#566 Enable inverse mass operator for simplex elements in all modules
  applications/incompressible_navier_stokes/vortex_periodic_bc/application.h
  include/exadg/compressible_navier_stokes/spatial_discretization/operator.cpp
  include/exadg/compressible_navier_stokes/user_interface/parameters.h
  include/exadg/convection_diffusion/spatial_discretization/operator.cpp
  include/exadg/convection_diffusion/user_interface/parameters.h
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_coupled.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/incompressible_navier_stokes/user_interface/enum_types.h
  include/exadg/incompressible_navier_stokes/user_interface/parameters.cpp
  include/exadg/incompressible_navier_stokes/user_interface/parameters.h
  include/exadg/operators/inverse_mass_operator.h
  include/exadg/operators/inverse_mass_parameters.h
  include/exadg/operators/operator_base.h
  include/exadg/solvers_and_preconditioners/preconditioners/elementwise_preconditioners.h
  include/exadg/solvers_and_preconditioners/preconditioners/inverse_mass_preconditioner.h
  include/exadg/solvers_and_preconditioners/solvers/iterative_solvers_dealii_wrapper.h
  include/exadg/solvers_and_preconditioners/solvers/wrapper_elementwise_solvers.h
Labels: simplex
