Repository exadg/exadg, pull requests merged in 2024-10, with the labels that each got.

#661 Use new `dealii::MatrixFreeTools` functions for diagonal computation and matrix assembly
  include/exadg/operators/operator_base.cpp
  include/exadg/operators/operator_base.h
Labels: deal.II update

#677 Enable DualSplitting and Pressure Correction for Simplex Elements
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_dual_splitting.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/operator_pressure_correction.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.cpp
  include/exadg/incompressible_navier_stokes/spatial_discretization/spatial_operator_base.h
  include/exadg/incompressible_navier_stokes/user_interface/parameters.cpp
Labels: simplex, matrix-free

#703 Enable matrix-based evaluation in Poisson throughput studies
  applications/poisson/gaussian/tests/gaussian.output
  applications/poisson/sine/tests/cartesian.output
  applications/poisson/sine/tests/curvilinear.output
  applications/poisson/throughput/application.h
  include/exadg/poisson/spatial_discretization/operator.cpp
  include/exadg/poisson/user_interface/parameters.cpp
  include/exadg/poisson/user_interface/parameters.h
Labels: new feature

#708 fix computation of unique dofs per element for throughput studies
  include/exadg/operators/finite_element.h
  include/exadg/operators/hypercube_resolution_parameters.h
Labels: simplex
